hmrc/income-tax-view-change-frontend

app/controllers/SessionTimeoutController.scala, app/views/timeout/timeout.scala.html, conf/app.routes, conf/messages, project/FrontendBuild.scala, test/assets/Messages.scala, test/controllers/SessionTimeoutControllerSpec.scala, test/routes/RoutesSpec.scala, test/views/SessionTimeoutViewSpec.scala
**Note**
At the moment, the sign-in button re-directs to the HellWorld page. This will need to be re-wired to re-direct the user to either the GG sign in page or to our HomeController (which will in turn re-direct to GG sign-in once the authentication piece has been implemented).
=> BTAT-94: Added Session Timeout Route, Controller, View and Tests

app/connectors/EstimatedTaxLiabilityConnector.scala, app/connectors/RawResponseReads.scala, app/models/ConnectorResponseModel.scala, app/models/EstimatedTaxLiabilityResponseModel.scala, app/services/EstimatedTaxLiabilityService.scala, conf/application.conf, project/FrontendBuild.scala, test/connectors/EstimatedTaxLiabilityConnectorSpec.scala, test/connectors/MockHttp.scala, test/services/EstimatedTaxLiabilityServiceSpec.scala, test/services/MockFinancialDataConnector.scala
**Notes:**
- This was branched off BTAT-115, please merge #13 prior to this.
- The connector converts the JSON response to the EstimatedTaxLiability model using the implicit format on the model (read & writes).
- If the connector responds with an error then it propagates the response to the calling method. (i.e. the controller).
=> [BTAT-118] - Added EstimatedTaxLiability service to call connector and translate JSON to model

app/controllers/SignInController.scala, app/controllers/predicates/AuthenticationPredicate.scala, app/views/timeout/timeout.scala.html, conf/app.routes, conf/application.conf, it/controllers/EstimatedTaxLiabilityControllerISpec.scala, it/controllers/ObligationsControllerISpec.scala, it/helpers/WiremockHelper.scala, test/controllers/EstimatedTaxLiabilityControllerSpec.scala, test/controllers/ObligationsControllerSpec.scala, test/controllers/SignInControllerSpec.scala, test/controllers/predicates/AuthenticationPredicateSpec.scala, test/utils/TestSupport.scala, test/views/timeout/SessionTimeoutViewSpec.scala
This PR fixes an issue where the Session Timeout was not working as expected.
This was due to the new Frontend Bootsrap having a Session Timeout Filter which wipes the authentication information from the session.
This PR checks if there is a `lastRequestTimestamp` in the header. If there is, but there is no `authToken` (Bearer Token) then the session has been wiped by the filter. Hence, redirect to Session Timeout View.
**Note**
A new SignIn controller has been introduced so that all the SignIn redirects can be handled by one controller.
=> [BTAT-230] Improved Session Timeout Handling

app/testOnly/TestOnlyAppConfig.scala, app/testOnly/connectors/DynamicStubConnector.scala, app/testOnly/controllers/StubDataController.scala, app/testOnly/controllers/StubSchemaController.scala, app/testOnly/forms/StubDataForm.scala, app/testOnly/forms/StubSchemaForm.scala, app/testOnly/forms/validation/Constraints.scala, app/testOnly/forms/validation/ErrorMessageFactory.scala, app/testOnly/forms/validation/ErrorMessageHelper.scala, app/testOnly/forms/validation/models/ErrorMessage.scala, app/testOnly/forms/validation/models/FieldError.scala, app/testOnly/forms/validation/models/SummaryError.scala, app/testOnly/forms/validation/models/TargetIds.scala, app/testOnly/forms/validation/utils/ConstraintUtil.scala, app/testOnly/forms/validation/utils/MappingUtil.scala, app/testOnly/forms/validation/utils/Patterns.scala, app/testOnly/models/DataModel.scala, app/testOnly/models/SchemaModel.scala, app/testOnly/views/helpers/continueButton.scala.html, app/testOnly/views/helpers/dropdownHelper.scala.html, app/testOnly/views/helpers/fieldErrorHelper.scala.html, app/testOnly/views/helpers/inputHelper.scala.html, app/testOnly/views/helpers/summaryErrorHelper.scala.html, app/testOnly/views/helpers/textAreaHelper.scala.html, app/testOnly/views/stubDataView.scala.html, app/testOnly/views/stubSchemaView.scala.html, app/testOnly/views/templates/stub_template.scala.html, conf/application.conf, conf/testOnlyDoNotUseInAppConf.routes
This PR adds testOnly routes, views, controller, connectors, form, models et al. which enables you to populate the dynamic stub with test data via an easily accessible view.
TestOnly routes are not deployed to production - they are only for the benefit of the team - hence no Unit Tests. 
TestOnly is excluded from scoverage
=> add-test-only-stub-view: Added testOnly route views to add data to Dynamic Stub

app/controllers/EstimatedTaxLiabilityController.scala, app/views/obligations.scala.html, conf/app.routes, it/controllers/EstimatedTaxLiabilityControllerISpec.scala, it/helpers/ComponentSpecBase.scala, test/assets/TestConstants.scala, test/connectors/LastTaxCalculationConnectorSpec.scala, test/controllers/EstimatedTaxLiabilityControllerSpec.scala, test/mocks/controllers/predicates/MockIncomeSourceDetailsPredicate.scala, test/mocks/services/MockIncomeSourceDetailsService.scala, test/models/BusinessListResponseModelSpec.scala, test/routes/RoutesSpec.scala, test/views/ObligationsViewSpec.scala
Routing is determined by the Accounting Period End Date of Income Source Models returned.
I.e., the earliest Tax Year will be the redirect URL route.
=> [BTAT-258] Update controller to redirect to earliest Tax Year estimate

app/connectors/BusinessDetailsConnector.scala, app/connectors/BusinessObligationDataConnector.scala, app/connectors/CalculationDataConnector.scala, app/connectors/PropertyDetailsConnector.scala, app/connectors/PropertyObligationDataConnector.scala, conf/logback.xml, it/helpers/WiremockHelper.scala, it/helpers/servicemocks/SelfAssessmentStub.scala
This fixes issue #74 
**Important**
Their is an associated PR on the itvc-dynamic-stub to correct the URL endpoint:
[BTAT-298 Stub PR](https://github.tools.tax.service.gov.uk/HMRC/itvc-dynamic-stub/pull/13)
=> [BTAT-298] Corrected calls to self-assessment-api microservice

app/controllers/predicates/AuthenticationPredicate.scala, app/utils/ImplicitDateFormatter.scala, app/views/estimatedTaxLiability.scala.html, app/views/helpers/ObSecHelper.scala.html, app/views/helpers/TaxYearRenderHelper.scala, conf/messages, public/stylesheets/itvc.css, test/assets/Messages.scala, test/views/EstimatedTaxLiabilityViewSpec.scala, test/views/ObligationsViewSpec.scala
Also added some content changes for v0.10.0 of proto from BTAT-268.
- Corrected obligation table styling
- Update the Estimated Tax Liability title and heading
- Updated 'Accounting period' to 'Report period'
- Added the sentence to warn users that their estimate may change
**Note**
There is also a minor fix to the authentication predicate to catch unexpected errors and throw ISE. Any auth errors will return to sign-in unless it is for an insufficient enrolments exception or timed out bearer token.
=> [BTAT-274] Added in-year estimate timestamp (date)

app/config/frontendAppConfig.scala, app/controllers/notEnrolled/NotEnrolledController.scala, app/controllers/predicates/AuthenticationPredicate.scala, app/views/notEnrolled/notEnrolled.scala.html, conf/app.routes, conf/application.conf, conf/messages, test/assets/Messages.scala, test/controllers/NotEnrolledControllerSpec.scala, test/controllers/predicates/AsyncActionPredicateSpec.scala, test/routes/RoutesSpec.scala, test/views/notEnrolled/NotEnrolledViewSpec.scala
**Note**
- Please merge app-config-base PR before merging this.
https://github.tools.tax.service.gov.uk/HMRC/app-config-base/pull/724
There is also a styling fix for the session-timeout page.
=> [BTAT-351] Added the not-enrolled view and handling

app/config/frontendAppConfig.scala, app/connectors/BusinessDetailsConnector.scala, app/connectors/BusinessReportDeadlinesConnector.scala, app/connectors/CalculationDataConnector.scala, app/connectors/LastTaxCalculationConnector.scala, app/connectors/PropertyDetailsConnector.scala, app/connectors/PropertyReportDeadlineDataConnector.scala, app/connectors/ServiceInfoPartialConnector.scala, app/connectors/UserDetailsConnector.scala, test/connectors/BusinessDetailsConnectorSpec.scala, test/connectors/BusinessReportDeadlinesConnectorSpec.scala, test/connectors/CalculationDataConnectorSpec.scala, test/connectors/LastTaxCalculationConnectorSpec.scala, test/connectors/PropertyDetailsConnectorSpec.scala, test/connectors/PropertyReportDeadlinesConnectorSpec.scala, test/connectors/ServiceInfoPartialConnectorSpec.scala, test/connectors/UserDetailsConnectorSpec.scala, test/utils/TestSupport.scala
- Changed the connectors to have the frontend app config injected into them - removing the need to override `mode` and `runmode` configuration continually as this is already catered for in the FrontendAppConf
=> [Inject-Frontend-App-Config] Inject the frontend app config into connectors

app/connectors/PropertyEOPSDeadlinesConnector.scala, test/connectors/PropertyEOPSDeadlinesConnectorSpec.scala
There is currently no endpoint defined for Property EOPS on the SA API service. Therefore the URL has been assumed based on similar endpoints. I have included a TODO comment to ensure that we revisit this once the endpoint is available.
The call to retrieve EOPS for property will be featureswitched until the enpoint is available in production.
=> [BTAT-1708] Added Property EOPS Connector, note: assumed URL

app/audit/AuditingService.scala, app/audit/models/AuditModel.scala, app/audit/models/EstimatesAuditing.scala, app/audit/models/ExitSurveyAuditing.scala, app/audit/models/ExtendedAuditModel.scala, app/audit/models/IncomeSourceDetailsRequestAuditModel.scala, app/audit/models/IncomeSourceDetailsResponseAuditModel.scala, app/audit/models/NinoLookupAuditing.scala, app/audit/models/ReportDeadlinesAuditing.scala, app/connectors/IncomeSourceDetailsConnector.scala, app/controllers/BaseController.scala, app/controllers/BusinessDetailsController.scala, app/controllers/predicates/IncomeSourceDetailsPredicate.scala, app/services/IncomeSourceDetailsService.scala, test/assets/TestConstants.scala, test/audit/mocks/MockAuditingService.scala, test/audit/models/IncomeSourceDetailsRequestAuditModelSpec.scala, test/audit/models/IncomeSourceDetailsResponseAuditModelSpec.scala, test/connectors/IncomeSourceDetailsConnectorSpec.scala, test/controllers/BaseControllerSpec.scala, test/controllers/BusinessDetailsControllerSpec.scala, test/mocks/connectors/MockIncomeSourceDetailsConnector.scala, test/mocks/services/MockIncomeSourceDetailsService.scala, test/services/IncomeSourceDetailsServiceSpec.scala, test/utils/TestSupport.scala
Based on Draft TxM Assessment here:
https://confluence.tools.tax.service.gov.uk/pages/viewpage.action?pageId=101666902
- Includes minor refactor of existing auditing events
- Path is extracted from the Referrer on the Request Header
- Uses ExtendedAuditModel based (despite deprecation warning) based on conversation with the TxM team
=> [BTAT-1966] Added Auditing to the calls to API#5 (Get Business Details)

app/connectors/ReportDeadlinesConnector.scala, test/connectors/ReportDeadlinesConnectorSpec.scala
This connector calls the new endpoint on our protected service to retrieve Report Deadlines (Obligations) from DES API#1330 direct.
=> [BTAT-2253] Create generic ReportDeadlinesConnector

app/config/features/Feature.scala, it/controllers/AccountDetailsControllerISpec.scala, it/controllers/BillsControllerISpec.scala, it/controllers/BusinessDetailsControllerISpec.scala, it/controllers/CalculationControllerISpec.scala, it/controllers/EstimatesControllerISpec.scala, it/controllers/HomeControllerISpec.scala, it/controllers/ReportDeadlinesControllerISpec.scala, it/controllers/StatementsControllerISpec.scala, it/helpers/ComponentSpecBase.scala, it/helpers/GenericStubMethods.scala, it/helpers/servicemocks/SelfAssessmentStub.scala
Includes minor tweaks:
- Authorised User is now on a `beforeEach()` rather than `beforeAll()` so that the authorised state is always guaranteed for each specific test. Unless overidden to unathorised. This was due to an unauthorised test bleeding into the following test.
- Made the last test the disabled test so that the assumed default can be enabled.
=> [BTAT-2411] Introduce and use common verification methods.

app/connectors/CalculationDataConnector.scala, app/models/calculation/CalcDisplayModel.scala, app/models/calculation/CalculationDataResponseModel.scala, app/models/models.scala, app/views/helpers/calcBreakdownHelper.scala.html, conf/messages, conf/messages.cy, it/assets/CalcDataIntegrationTestConstants.scala, it/controllers/CalculationControllerISpec.scala, test/assets/CalcBreakdownTestConstants.scala, test/models/CalculationDataResponseModelSpec.scala, test/models/CalculationResponseModelSpec.scala, test/views/CrystallisedViewSpec.scala, test/views/helpers/CalcBreakdownHelperSpec.scala
Updated to receive and use new structure for income tax bands
Changed how income tax bands were displayed to allow any number of bands
Updated with new tests for scottish rates with SRT and IRT
=> MIT-27 - Use new income structure, display scottish tax bands

app/models/calculation/CalculationDataResponseModel.scala, app/views/helpers/calcBreakdownHelper.scala.html, conf/messages, test/assets/CalcBreakdownTestConstants.scala, test/assets/Messages.scala, test/models/CalculationResponseModelSpec.scala, test/views/helpers/CalcBreakdownHelperSpec.scala
User should be able to see national Regime on estimate page
Add new attribute national regime to model and display it on UI and fix model and UI tests
=> Mit 32:User Subject to Non-UK Rates of Income Tax

app/config/FrontendAppConfig.scala, app/controllers/SignOutController.scala, test/controllers/SignOutControllerSpec.scala
After signout the user is redirected to the feedback survey with the following identifiers:
- `ITVCA` identifier for an `Agent` user
- `ITVC` identifier for any non-`Agent` user
=> MISUV-1746 Exit Survey Feedback by User Type

app/config/featureswitch/FeatureSwitch.scala, app/config/featureswitch/FeatureSwitching.scala, app/controllers/ReportDeadlinesController.scala, conf/application.conf, it/controllers/ReportDeadlinesControllerISpec.scala, test/config/featureswitch/FeatureSwitchingSpec.scala, test/controllers/ReportDeadlinesControllerSpec.scala
- behavior left as if the switch was enabled
- switch removed from code and application.conf file
- removed tests for a "disabled" state of the switch
- refactoring of the ReportDeadlinesController
=> MISUV-1394: Remove the Enable Report Deadlines Feature switch

app/config/FrontendAppConfig.scala, conf/application.conf, it/controllers/FinalTaxCalculationControllerISpec.scala, it/controllers/agent/FinalTaxCalculationControllerISpec.scala, test/views/HomePageViewSpec.scala, test/views/agent/HomePageViewSpec.scala
Change all `/income-through-software/return/` strings to `/update-and-submit-income-tax-return/`
[SASS-1564](https://jira.tools.tax.service.gov.uk/browse/SASS-1564)
=> SASS-1564: Update V&C page URLs

app/views/FinalTaxCalculationView.scala.html, app/views/InYearTaxCalculationView.scala.html, app/views/components/h1_itsa.scala.html, app/views/layouts/layout.scala.html, it/controllers/FinalTaxCalculationControllerISpec.scala, it/controllers/InYearTaxCalculationControllerISpec.scala, it/controllers/agent/FinalTaxCalculationControllerISpec.scala, it/controllers/agent/InYearTaxCalculationControllerISpec.scala
SASS-2499 
Accessibility fixes from ticket [SASS-2499](https://jira.tools.tax.service.gov.uk/browse/SASS-2499)
Final Tax Overview Page: Link missing gov.uk style
Final Tax Overview and In year estimate Page: Heading structure
Final Tax Overview and In Year Tax Estimate Page: Remove the HMRC Banner
=> SASS-2499a accessibility fixes to banner, heading & link

app/views/layouts/layout.scala.html
SASS-2499
Accessibility fixes
- hide HMRC banner on in year tax estimate & final tax overview pages
- update help link text on in year tax estimate & final tax overview pages
=> SASS-2500 accessibility fix hmrc banner

app/controllers/HomeController.scala, app/views/Home.scala.html, conf/messages, conf/messages.cy, test/views/HomePageViewSpec.scala
* dynamically change 'claim and refund link' on the home page, depending on the user migration status;
* add required english/welsh resource for link title;
* fix broken unit tests + add addition tests to cover case where user not migrated;
=> MISUV-3711: change home page link based on the migration status

app/models/CreditDetailModel.scala, app/services/CreditHistoryService.scala, test/services/CreditHistoryServiceSpec.scala, test/services/helpers/CreditHistoryDataHelper.scala
* yet another rework for CreditHistoryService;
* add date to CreditDetailModel
* extract CreditDetailModel.date for MFA and CutOver credit in a the different way;
* extract credit for (taxYear + taxYear + 1) than filter by date to get required calendarYear credits;
* required unit test coverage added
=> MISUV-3860: CreditHistoryService rework number 2

app/utils/CreditAndRefundUtils.scala, test/testConstants/FinancialDetailsTestConstants.scala, test/utils/CreditAndRefundUtilsSpec.scala
Fix the bug for identifying a payment we need to check the existence of **paymentLot** and **paymentLotItem** fields on the **documentDetail**. And not the **mainType** contains "Payment on Account"
=> MISUV-4336 Bug fix for the payment type

app/audit/models/TaxYearSummaryResponseAuditModel.scala, app/controllers/HomeController.scala, app/controllers/NextUpdatesController.scala, app/controllers/SignOutController.scala, app/controllers/agent/EnterClientsUTRController.scala, app/controllers/predicates/AuthenticationPredicate.scala, app/controllers/predicates/IncomeSourceDetailsPredicate.scala, app/controllers/predicates/IncomeSourceDetailsPredicateNoCache.scala, app/controllers/predicates/NinoPredicate.scala, app/testOnly/controllers/StubDataController.scala, app/testOnly/controllers/StubSchemaController.scala, app/views/Home.scala.html, app/views/partials/taxYearSummaryTabsPartial.scala.html, build.sbt
* suppress warning 'multiarg-infix' warning at the moment;
* fix next warning's => 'Auto-application to `()` is deprecated'
At this moment FE contains just 11 warnings => next sets of stories to resolve these => [enforce compile failure on warning](https://jira.tools.tax.service.gov.uk/browse/MISUV-4437)
=> MISUV-4408: tidy up warning during compilation / scala upgrade to 2.13.8 left over 

it/controllers/WhatYouOweControllerISpec.scala, it/controllers/agent/WhatYouOweControllerISpec.scala, it/testConstants/FinancialDetailsIntegrationTestConstants.scala
Removed all instances of LocalDate.now from the two WhatYouOweControllerISpecs, replaced with a static date. All changes to FinancialDetailsIntegrationTestConstants.scala only affect constants which are only used by WhatYouOweControllerISpec(s)
=> Misuv 4834 - WhatYouOweControllerISpec(s): remove usage of LocalDate.now

app/controllers/ChargeSummaryController.scala, app/controllers/CreditAndRefundController.scala, app/controllers/HomeController.scala, app/controllers/InYearTaxCalculationController.scala, app/controllers/TaxYearSummaryController.scala, app/controllers/TaxYearsController.scala, app/controllers/WhatYouOweController.scala, app/models/financialDetails/DocumentDetail.scala, app/models/financialDetails/FinancialDetail.scala, app/models/financialDetails/FinancialDetailsResponseModel.scala, app/services/DateService.scala, app/services/FinancialDetailsService.scala, app/services/NextUpdatesService.scala, app/services/PaymentHistoryService.scala, app/services/WhatYouOweService.scala, it/controllers/HomeControllerISpec.scala, it/controllers/InYearTaxCalculationControllerISpec.scala, it/controllers/WhatYouOweControllerISpec.scala, it/controllers/agent/HomeControllerISpec.scala, it/controllers/agent/InYearTaxCalculationControllerISpec.scala, it/helpers/ComponentSpecBase.scala, it/helpers/agent/ComponentSpecBase.scala, it/testConstants/BaseIntegrationTestConstants.scala, it/testConstants/FinancialDetailsIntegrationTestConstants.scala, it/testConstants/NextUpdatesIntegrationTestConstants.scala, it/testConstants/OutstandingChargesIntegrationTestConstants.scala
* redesign DateService usage across controller: we would use DateServiceInterface instead;
* remove usage of LocalDate.now where needed + override required methods of DateService in the scope of it:test to remove dynamic date and time generation;
Fixes for it/controllers/InYearTaxCalculationControllerISpec would be part of another PR (still under investigation)
=> MISUV-5354: Fix build / it:tests failures

app/views/ChargeSummary.scala.html, it/controllers/ChargeSummaryControllerISpec.scala, it/controllers/agent/ChargeSummaryControllerISpec.scala, it/testConstants/messages/ChargeSummaryMessages.scala, project/plugins.sbt, test/views/ChargeSummaryViewSpec.scala
added .toString so that the ints aren't formatted incorrectly
=> MISUV-5370: Incorrect date format getting displayed on coding out summary page

app/config/FrontendAppConfig.scala, app/connectors/IncomeTaxViewChangeConnector.scala, app/utils/Headers.scala, conf/application.conf, test/connectors/IncomeTaxViewChangeConnectorSpec.scala, test/utils/HeadersSpec.scala
* refactor code to read incomeSource overrides from app~.config; we can change single string in the application.config file without recompilation apply required changes
=> MISUV-5914: avoiding re-compilation when changing read incomeSource override

app/models/core/IncomeSourceIdHash.scala, test/models/incomeSourceDetails/IncomeSourceIdHashSpec.scala, test/models/incomeSourceDetails/IncomeSourceIdHashSpecification.scala
* reduce chances of hashCode duplication
For local run N times:
```
for value in {1..100}
do
sbt "testOnly models.incomeSourceDetails.IncomeSourceIdHashSpecification"
done
```
=> MISUV-6526:: enhance incomeSourceId hashing 

app/controllers/incomeSources/add/IncomeSourceAddedController.scala
* IncomeSourceId evaluation: use .value instead of .toString;
=> MISUV-6480: incomeSourceId - use .value instead of .toString

it/connectors/NavBarEnumFsConnectorISpec.scala
When built in IntelliJ, both the UTs and ATs are built to the same directory (test-classes) and the import for the helpers package picks up a local package from the UT erroneously. By using an absolute import, this problem is avoided.
=> Fix compilation issue in IntelliJ by using absolute imports

build.sbt, it/test/connectors/NavBarEnumFsConnectorISpec.scala, it/test/controllers/CalculationPollingControllerISpec.scala, it/test/controllers/CreditsSummaryControllerISpec.scala, it/test/controllers/HomeControllerISpec.scala, it/test/controllers/PaymentHistoryControllerISpec.scala, it/test/controllers/TaxDueSummaryControllerISpec.scala, it/test/controllers/agent/CalculationPollingControllerISpec.scala, it/test/controllers/agent/TaxDueSummaryControllerISpec.scala, it/test/controllers/agent/UTRErrorControllerISpec.scala, it/test/controllers/agent/incomeSources/add/AddIncomeSourceStartDateControllerISpec.scala, it/test/controllers/agent/incomeSources/add/IncomeSourceReportingMethodControllerISpec.scala, it/test/controllers/agent/incomeSources/add/IncomeSourceReportingMethodNotSavedControllerISpec.scala, it/test/controllers/agent/incomeSources/cease/IncomeSourceCeasedBackErrorControllerISpec.scala, it/test/controllers/agent/incomeSources/manage/ManageObligationsControllerISpec.scala, it/test/controllers/agent/incomeSources/manage/ReportingMethodErrorControllerISpec.scala, it/test/controllers/incomeSources/add/IncomeSourceReportingMethodControllerISpec.scala, it/test/controllers/incomeSources/manage/ManageObligationsControllerISpec.scala, it/test/controllers/incomeSources/manage/ReportingMethodErrorControllerISpec.scala, it/test/helpers/CustomMatchers.scala, it/test/helpers/agent/SessionCookieCrumbler.scala, it/test/helpers/servicemocks/BtaNavBarPartialConnectorStub.scala, it/test/repositories/UIJourneySessionDataISpec.scala, it/test/testConstants/PaymentHistoryTestConstraints.scala
Next scalaFix rules applied across it project:
RemoveUnused.imports = true
RemoveUnused.privates = true
RemoveUnused.locals = true
RemoveUnused.patternvars = true
RemoveUnused.params = true
=> MISUV-6988: it:tests / remove not used imports

it/test/controllers/CreditAndRefundControllerISpec.scala, it/test/controllers/agent/CalculationPollingControllerISpec.scala, it/test/controllers/agent/CreditAndRefundControllerISpec.scala, it/test/controllers/agent/DeductionsSummaryControllerISpec.scala, it/test/controllers/agent/FinalTaxCalculationControllerISpec.scala, it/test/controllers/agent/ForecastIncomeSummaryControllerISpec.scala, it/test/controllers/agent/ForecastTaxCalcSummaryControllerISpec.scala, it/test/controllers/agent/IncomeSummaryControllerISpec.scala, it/test/controllers/agent/NextUpdatesControllerISpec.scala, it/test/controllers/agent/PaymentAllocationsControllerISpec.scala, it/test/controllers/agent/PaymentControllerISpec.scala, it/test/controllers/agent/PaymentHistoryControllerISpec.scala, it/test/controllers/agent/TaxDueSummaryControllerISpec.scala, it/test/controllers/agent/TaxYearSummaryControllerISpec.scala, it/test/controllers/agent/TaxYearsControllerISpec.scala
replace LocalDate.now() with fixedDate in it/test
=> MISUV-6871: LocalDate.now removal from unit tests and it:Tests

app/controllers/ChargeSummaryController.scala, app/controllers/NextUpdatesController.scala, app/controllers/PaymentAllocationsController.scala, test/controllers/ChargeSummaryControllerSpec.scala, test/controllers/ChargeSummaryControllerTest.scala
* - change in the next set of controllers / auth for agents to be aligned with the rest of the code =>
** - PaymentAllocationsController;
**  - NextUpdatesController;
** - ChargeSummaryController;
There are sill occurrences of old style auth approach in other controller like:
ForecastIncomeSummaryController / but FS load in case of read from mongo is addressed in the different way;
Next story is created to address remaining changes https://jira.tools.tax.service.gov.uk/browse/MISUV-7776
=> MISUV-7256: FS Patch V3 / STAGING only

app/controllers/WhatYouOweController.scala, app/models/financialDetails/DocumentDetail.scala, app/models/financialDetails/WhatYouOweChargesList.scala, app/services/ClaimToAdjustHelper.scala, app/views/WhatYouOwe.scala.html, conf/messages, conf/messages.cy, it/test/controllers/WhatYouOweControllerISpec.scala, test/testConstants/FinancialDetailsTestConstants.scala, test/views/WhatYouOweViewSpec.scala
When both POA 1 and POA 2 are paid i.e. no payments on account due on 'What you owe' (WYO) page, we display the option to adjust POAs with some content.
=> MISUV-7766 | Claim to Adjust POA | Update - Option (entry point) for adjusting POAs on WYO page

app/services/optout/OptOutService.scala, test/services/optout/OptOutServiceSpec.scala
This PR removes the need, within the handling of the submit action from the Opt Out Confirmation Page, to persist the tax year to opt-out for in mongo, just to pull it back again in the next function.
This simplification should make it easier to persist the 3 ITSA statuses and the Crystallised status to mongo, giving a consistent context in which to generate all the pages in the journey and to address the recent issues we've seen in E2E testing.
Moreover, I think the original code could have had a race condition in it in that the write to the DB was implemented async, yet not waited for before reading it back. Thought I've not reproduce the race condition, I think we're safer without this possibility.
I would have liked to go further and transform the `makeOptOutUpdateRequest()` function …
=> Misuv 7945 remove use of mongo in 1 year opt out

app/services/claimToAdjustPoa/ClaimToAdjustHelper.scala, it/test/testConstants/IncomeSourceIntegrationTestConstants.scala, test/services/claimToAdjust/ClaimToAdjustServiceSpec.scala, test/testConstants/claimToAdjustPOA/ClaimToAdjustPOATestConstants.scala
amended the getChargeHistory method in ClaimToAdjustHelper to fetch only POA charge histories, rather than just grabbing the item at the top of the list
=> MISUV-7810-ctaService-getCH-fetch-poa-charge-not-head

app/controllers/NextUpdatesController.scala, app/services/CalculationListService.scala, app/services/optout/OptOutService.scala, test/controllers/NextUpdatesControllerSpec.scala, test/controllers/optOut/OptOutChooseTaxYearControllerSpec.scala, test/mocks/services/MockCalculationListService.scala, test/mocks/services/MockDateService.scala, test/mocks/services/MockOptOutService.scala, test/services/optout/OptOutServiceNextUpdatesPageOptOutViewModelSpec.scala, test/services/optout/OptOutServiceSpec.scala
Prevents 2 calls to get Opt Out data when showing the Next Updates page.
This PR replaces [the previous PR](https://github.com/hmrc/income-tax-view-change-frontend/pull/2382) that now has too many conflicts to easily merge.
=> MISUV 7885 reduce opt out api calls in next updates controller

app/views/PaymentHistory.scala.html
Added a short line in the view page to change the font size to 16.5 for the tax year credits
=> MISUV-7973 Payment, credit and refund history tax year font size should match V&C service pages

app/connectors/BusinessDetailsConnector.scala
Good day all prospective reviewers!!! The main goal of this PR was to change the logging level for a valid scenario from error to warning. This means that it will no longer clog up our Kibana logs with IRRELEVANT error logs! I also took the liberty to remove the use of a magic number in this here production code (404 -> NOT_FOUND). Hopefully, this would make the code more readable to anyone reading it.
I hope this change pleases you. Feel free to leave any comments below and I shall endeavour to address them at my earliest convenience. 
Good day.
Best regards,
Simon
=> MISUV-8098-logger-level-change 

app/models/chargeHistory/ChargeHistoryModel.scala
Loggers are not intended to be in Models, case error still returns string.
=> Remove logger from ChargeHistoryModel

app/auth/authV2/actions/AuthoriseAndRetrieve.scala
With AffinityGroup first in the agent Predicate, an UnsupportedAffinityGroup exception was returned instead of an InsufficientEnrolments exception when the HMRC-MTD-IT enrolment was missing.
This resulted in user being redirected to the incorrect page when the enrolment is missing (GG, instead of cannot-access-service). This causes [acceptance test fails](https://build.tax.service.gov.uk/job/Payments/job/self-assessment-refund-ui-tests/919/cucumber-html-reports/report-feature_3_3069762375.html) for self-assessment-refund-frontend.
**To reproduce**: 
Direct in to http://localhost:9949/auth-login-stub/gg-sign-in
Enter **Redirect URL**: http://localhost:9081/report-quarterly/income-and-expenses/view/claim-refund?origin=PTA
Enter **NINO**: AY888887A
Enter **Confidence Level**: 250
**Expected …
=> Auth fix | UnsupportedAffinityGroup being returned instead of InsufficentEnrolments

app/controllers/ReportingFrequencyPageController.scala, app/models/ReportingFrequencyViewModel.scala, app/services/optout/OptOutService.scala, app/views/ReportingFrequencyView.scala.html, app/views/components/linkComponent.scala.html, conf/messages, conf/messages.cy, it/test/controllers/NextUpdatesControllerISpec.scala, it/test/controllers/ReportingFrequencyControllerISpec.scala, it/test/testConstants/IncomeSourceIntegrationTestConstants.scala, test/controllers/ReportingFrequencyPageControllerSpec.scala, test/testUtils/TestSupport.scala, test/views/ReportingFrequencyViewSpec.scala, test/views/messages/ReportingFrequencyViewMessages.scala
opt out does not have a journey start page.
The logic for the links are off but we have tickets to update the link logic and have dynamic changing links for the page based on the user statuses and journey eligibility.
For now placing some logic as a placeholder and for demoing the page.
Had git history issues, cleaned up and using this pr/branch. For cleaner history.
=> MISUV-8687 Create new Reporting Frequency View

app/controllers/incomeSources/add/IncomeSourceReportingMethodController.scala, app/controllers/incomeSources/manage/ManageIncomeSourceDetailsController.scala, app/controllers/manageBusinesses/add/IncomeSourceReportingMethodController.scala, app/controllers/manageBusinesses/manage/ManageIncomeSourceDetailsController.scala, app/controllers/optOut/OptOutCancelledController.scala, app/controllers/optOut/OptOutChooseTaxYearController.scala, app/services/CalculationListService.scala, app/services/optout/OptOutService.scala, app/views/optOut/OptOutCancelledView.scala.html, it/test/controllers/optOut/OptOutCancelledControllerISpec.scala, test/controllers/incomeSources/add/IncomeSourceReportingMethodControllerSpec.scala, test/controllers/manageBusinesses/add/IncomeSourceReportingMethodControllerSpec.scala, test/controllers/optOut/OptOutCancelledControllerSpec.scala, test/mocks/services/MockCalculationListService.scala, test/services/CalculationListServiceSpec.scala, test/services/optout/OptOutServiceSpec.scala, test/views/optOut/OptOutCancelledViewSpec.scala
Added routing, had to adjust the logic to handle multi years  and moved it to the service out of the controller, hopefully making it easier to test and then cleaned up the tests. Page also handles when a tax year intent is not chosen, since there is cancel link for a multi year scenario. It allows the user to cancel before a year is chosen but the current view has content which depends on a chose tax year. Thus made the paragraph optional. Might need to check with design.
=> MISUV-8943 Add routing to opt out cancelled for multi year and update logic for determining tax year

app/viewmodels/govuk/DateFluency.scala
Only the `withHint` method is being used. Checked if similar code to the deleted methods was being implemented, with the hunch that there may be duplicate code but none found.
=> MISUV-8917 - Refactor FluentDate

app/config/FrontendAppConfig.scala, app/controllers/optOut/ConfirmedOptOutController.scala, app/enums/ChosenTaxYear.scala, app/services/optout/OptOutService.scala, app/viewUtils/ConfirmedOptOutViewUtils.scala, app/views/optOut/ConfirmedOptOut.scala.html, conf/application.conf, conf/messages, conf/messages.cy, it/test/controllers/optOut/ConfirmedOptOutControllerISpec.scala, test/controllers/optOut/ConfirmedOptOutControllerSpec.scala, test/viewUtils/ConfirmedOptOutViewUtilsSpec.scala, test/views/messages/ConfirmedOptOutMessages.scala, test/views/optOut/ConfirmedOptOutViewSpec.scala
Requirements and scenarios covered in the ticket is a bit weird, basically we showed content for the submit your tax return with no logic originally.
However, we are now according to the ticket displaying logic based on itsa statuses & CY & CY+1 choices.
The scenarios covered in the ticket miss out single tax year choice scenarios and possible CY-1 choices. This has been raised with Bethrand and also other combinations of itsa statuses.
After speaking with Bethrand it is likely we ultimately only really care about the user's chosen intent tax year and not the combination of itsa statuses. But atm not sure so coded out the ticket logic. A comment has been raised to raise a ticket for other scenarios.
**Update:** 
Have a feeling we may need to for now add content for the previous years and …
=> MISUV-9007 Adding scenario based content for optout confirmed page

app/views/WhatYouOwe.scala.html, test/services/WhatYouOweServiceSpec.scala, test/testConstants/ChargeConstants.scala, test/testConstants/FinancialDetailsTestConstants.scala
Current mappings (see MISUV-8845) say that both of these values should come from balanceDetails.availableCredit, so have changed both to that
=> MISUV-5422 Same message with different amounts getting displayed on WYO page

app/controllers/ChargeSummaryController.scala, app/models/financialDetails/FinancialDetailsResponseModel.scala, app/services/CreditHistoryService.scala, app/services/WhatYouOweService.scala, app/services/claimToAdjustPoa/ClaimToAdjustService.scala, it/test/controllers/TaxYearSummaryControllerISpec.scala, it/test/controllers/WhatYouOweControllerISpec.scala, it/test/controllers/YourSelfAssessmentChargesControllerISpec.scala, test/controllers/ChargeSummaryControllerSpec.scala
In this PR one small change applied in FinancialDetailsResponseModel:
* next method removed as not required => documentDetailsFilter
* other changes as a result of this refactoring;
* Rename next method getPairedDocumentDetails => asChargeItems
=> Misuv 9397: API 1553 Refactoring / simplify FinancialDetailsResponseModel / drop documentDetailsFilter method

app/views/agent/SupportingAgentHome.scala.html, conf/messages, conf/messages.cy, test/views/agent/SupportingAgentHomePageViewSpec.scala
The link itself isn't live yet so clicking it currently just leads to a 404.
=> [MISUV-9594] Adding guidance link to supporting agents front page

app/models/paymentAllocationCharges/PaymentAllocationViewModel.scala
** - throw and error if paymentLotItem and/or paymentLot not present;
Original PR:
https://github.com/hmrc/income-tax-view-change-frontend/pull/2864/files
=> * MISUV-9650: revert changes

app/models/financialDetails/DocumentDetail.scala, test/services/FinancialDetailsServiceSpec.scala
Class 2 Nics was being shown even with 0 outstanding amount, as it was being treated as a coded out charge, but Class 2 Nics can't be coded out
=> Fixed bug with class 2 Nics

app/views/ForecastTaxCalcSummary.scala.html, app/views/claimToAdjustPoa/CheckYourAnswers.scala.html, app/views/claimToAdjustPoa/EnterPoaAmountView.scala.html, app/views/incomeSources/add/IncomeSourceAddedObligations.scala.html, app/views/optOut/ConfirmedOptOut.scala.html, app/views/partials/chargeSummary/ChargeSummaryCodingOut.scala.html
Updating view files to use components instead of the '<p>' tag.
There were a few files which have been left out such as the StubDataView and StubSchemaView. This was due to running into errors when changing these files to use the component. As these files are testOnly files, I think it's okay to leave as is.
=> MISUV-9295 Updating view files to use p component
