- app/connectors/BusinessDetailsConnector.scala
- app/connectors/LastTaxCalculationConnector.scala
- app/controllers/EstimatedTaxLiabilityController.scala
- app/models/BusinessListResponseModel.scala
- app/services/BusinessDetailsService.scala
- app/services/EstimatedTaxLiabilityService.scala
- app/services/ObligationsService.scala
- app/views/estimatedTaxLiability.scala.html
- app/views/helpers/TaxYearRenderHelper.scala
- conf/logback-test.xml
- conf/messages
- it/controllers/EstimatedTaxLiabilityControllerISpec.scala
- it/controllers/ObligationsControllerISpec.scala
- it/helpers/IntegrationTestConstants.scala
- it/helpers/servicemocks/IncomeTaxViewChangeStub.scala
- it/helpers/servicemocks/SelfAssessmentStub.scala
- test/assets/TestConstants.scala
- test/connectors/BusinessDetailsConnectorSpec.scala
- test/connectors/LastTaxCalculationConnectorSpec.scala
- test/controllers/EstimatedTaxLiabilityControllerSpec.scala
- test/mocks/connectors/MockLastTaxCalculationConnector.scala
- test/mocks/services/MockBusinessDetailsService.scala
- test/mocks/services/MockEstimatedLiabilityService.scala
- test/models/BusinessListResponseModelSpec.scala
- test/services/BusinessDetailsServiceSpec.scala
- test/services/EstimatedTaxLiabilityServiceSpec.scala
- test/services/ObligationsServiceSpec.scala
- test/utils/TestSupport.scala
- test/views/EstimatedTaxLiabilityViewSpec.scala
- test/views/helpers/TaxYearRenderHelperSpec.scala
**NOTE**
This also includes the required changes for BTAT-9 which is to dynamically display the Payment Due Date based on the Tax Year.
Stub Change PR [here](https://github.tools.tax.service.gov.uk/HMRC/itvc-dynamic-stub/pull/10)
> [BTAT-229] TaxYear and Payment Due Date calculate from Accounting Period End Dated

- app/connectors/LastTaxCalculationConnector.scala
- app/connectors/PropertyDetailsConnector.scala
- app/connectors/PropertyObligationDataConnector.scala
- app/controllers/EstimatedTaxLiabilityController.scala
- app/controllers/predicates/AuthenticationPredicate.scala
- app/models/AccountingPeriodModel.scala
- app/models/BusinessListResponseModel.scala
- app/models/PropertyDetailsResponseModel.scala
- it/helpers/IntegrationTestConstants.scala
- test/connectors/BusinessDetailsConnectorSpec.scala
- test/connectors/BusinessObligationDataConnectorSpec.scala
- test/connectors/LastTaxCalculationConnectorSpec.scala
- test/connectors/PropertyDetailsConnectorSpec.scala
- test/connectors/PropertyObligationDataConnectorSpec.scala
- test/controllers/predicates/AuthenticationPredicateSpec.scala
- test/mocks/MockHttp.scala
- test/models/AccountingPeriodModelSpec.scala
- test/models/BusinessListResponseModelSpec.scala
Simplified Unit tests for connectors and added tests for failed futures (previously untested)
> [BTAT-250] Added Property Details Connector

- app/views/estimatedTaxLiability.scala.html
- conf/messages
- it/controllers/FinancialDataControllerISpec.scala
- test/assets/Messages.scala
- test/views/EstimatedTaxLiabilityViewSpec.scala
Also corrected Bus/Property profit issue on multiple tax years
> [BTAT-351] Updated prototype content v0.13.0

- app/config/frontendAppConfig.scala
- app/connectors/BusinessDetailsConnector.scala
- app/connectors/BusinessObligationDataConnector.scala
- app/connectors/CalculationDataConnector.scala
- app/connectors/PropertyDetailsConnector.scala
- app/connectors/PropertyObligationDataConnector.scala
- app/controllers/predicates/AuthenticationPredicate.scala
- conf/application.conf
- it/helpers/servicemocks/SelfAssessmentStub.scala
- test/connectors/BusinessDetailsConnectorSpec.scala
- test/connectors/BusinessObligationDataConnectorSpec.scala
- test/connectors/CalculationDataConnectorSpec.scala
- test/connectors/PropertyDetailsConnectorSpec.scala
- test/connectors/PropertyObligationDataConnectorSpec.scala
Reverts hmrc/income-tax-view-change-frontend#99
> Revert "[BTAT-246-Stub-Context] add itvc stub context route to config"

- app/forms/ExitSurveyForm.scala
- app/forms/constraints/Validation.scala
- app/models/ExitSurveyModel.scala
- conf/messages
- test/assets/Messages.scala
- test/forms/ExitSurveyFormSpec.scala
- test/forms/constraints/ValidationSpec.scala
Merging into BTAT-183-Story base branch.
> [BTAT-437] Added ExitSurveyModel and Form (with validation)

- app/models/AccountingPeriodModel.scala
- app/models/IncomeSourcesModel.scala
- app/views/estimatedTaxLiability.scala.html
- conf/messages
- test/assets/Messages.scala
- test/assets/TestConstants.scala
- test/controllers/FinancialDataControllerSpec.scala
- test/models/AccountingPeriodModelSpec.scala
- test/models/IncomeSourcesModelSpec.scala
- test/views/EstimatedTaxLiabilityViewSpec.scala
AT PR: https://github.tools.tax.service.gov.uk/HMRC/income-tax-view-change-frontend-acceptance-test/pull/26
> BTAT-359-Story: Story complete.

- app/forms/preprocess/XssFilter.scala
- test/forms/preprocess/XssFilterSpec.scala
> [BTAT-438] Added XssFilter

- app/views/report_deadlines.scala.html
- conf/messages
- test/assets/Messages.scala
- test/views/ReportDeadlinesViewSpec.scala
Changes to 'Estimates' and 'Report Deadlines'
> [BTAT1237-Story] Content changes for v2.6.0 of proto

- app/models/ObligationType.scala
- app/models/ReportDeadlinesResponseModel.scala
- app/views/templates/reportDeadlines/reportDeadlines_template.scala.html
- conf/messages
- it/controllers/ReportDeadlinesControllerISpec.scala
- it/helpers/IntegrationTestConstants.scala
- test/assets/Messages.scala
- test/assets/TestConstants.scala
- test/models/ReportDeadlinesResponseModelSpec.scala
- test/views/ReportDeadlinesViewSpec.scala
**NOTE** Raised on behalf of @LadonJackson from closed PR #259
> [BTAT-1758] Render EOPS Deadline on Report Deadlines Page (Obligations)

- app/config/features/Features.scala
- app/config/features/Keys.scala
- app/connectors/BusinessDetailsConnector.scala
- app/connectors/BusinessEOPSDeadlinesConnector.scala
- app/connectors/BusinessReportDeadlinesConnector.scala
- app/connectors/CalculationDataConnector.scala
- app/connectors/FinancialTransactionsConnector.scala
- app/connectors/LastTaxCalculationConnector.scala
- app/connectors/NinoLookupConnector.scala
- app/connectors/PropertyDetailsConnector.scala
- app/connectors/PropertyEOPSDeadlinesConnector.scala
- app/connectors/PropertyReportDeadlinesConnector.scala
- app/services/ReportDeadlinesService.scala
- app/testOnly/controllers/FeatureSwitchController.scala
- app/testOnly/forms/FeatureSwitchForm.scala
- app/testOnly/models/FeatureSwitchModel.scala
- app/testOnly/views/featureSwitch.scala.html
- conf/application.conf
- test/connectors/BusinessEOPSDeadlinesConnectorSpec.scala
- test/connectors/PropertyEOPSDeadlinesConnectorSpec.scala
- test/connectors/PropertyReportDeadlinesConnectorSpec.scala
- test/mocks/connectors/MockBusinessEOPSDeadlinesConnector.scala
- test/mocks/connectors/MockPropertyEOPSDeadlinesConnector.scala
- test/mocks/connectors/MockPropertyReportDeadlinesConnector.scala
Note: Includes an intiital commit to refactor some of the names of the connectors and connector methods to be consistent. Also the scoping of the URLs is now limited to the connectors package.
> [BTAT-1766] Added feature switches for EOPS connector calls

- app/config/FrontendAppConfig.scala
- app/config/features/Keys.scala
- app/controllers/PaymentController.scala
- app/models/PaymentDataModel.scala
- app/testOnly/controllers/FeatureSwitchController.scala
- app/testOnly/forms/FeatureSwitchForm.scala
- app/testOnly/models/FeatureSwitchModel.scala
- app/testOnly/views/featureSwitch.scala.html
- app/utils/ImplicitCurrencyFormatter.scala
- app/views/crystallised.scala.html
- app/views/statements.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages
- test/assets/Messages.scala
- test/assets/TestConstants.scala
- test/controllers/BillsControllerSpec.scala
- test/controllers/PaymentControllerSpec.scala
- test/models/PaymentDataModelSpec.scala
- test/utils/CurrencyFormatterSpec.scala
- test/views/CrystallisedViewSpec.scala
- test/views/StatementsViewSpec.scala
AT PR: https://github.com/hmrc/income-tax-view-change-frontend-acceptance-test/pull/35
> [BTAT-14-Story] Payment Button and Link on Bills and Statements page

- app/views/statements.scala.html
Bug fix for #282 
**Note** No tests needed to change as the two amounts in the models match in our tests.
> [BTAT-2014] Corrected Statements View

- conf/messages
- it/controllers/BillsControllerISpec.scala
- test/assets/Messages.scala
- test/views/CrystallisedViewSpec.scala
- test/views/EstimatedTaxLiabilityViewSpec.scala
> [BTAT-2109] capitalised Income Tax and Self Assessment

- app/views/crystallised.scala.html
- app/views/home.scala.html
> [BTAT-2107] Removed 'how this figure was calculated' heading and and changed heading tags

- app/views/home.scala.html
> [BTAT-2160] fixed the bold sub heading on the homepage

- app/controllers/CalculationController.scala
> [BTAT-2197] Only call Financial Transactions when needed

- app/views/home.scala.html
- conf/messages
- test/assets/Messages.scala
- test/views/HomePageViewSpec.scala
> [BTAT-2360]: updated homepage content

- app/audit/AuditingService.scala
- app/audit/models/ReportDeadlinesRequestAuditModel.scala
- app/audit/models/ReportDeadlinesResponseAuditModel.scala
- app/connectors/IncomeSourceDetailsConnector.scala
- app/connectors/ReportDeadlinesConnector.scala
- app/controllers/CalculationController.scala
- app/controllers/ExitSurveyController.scala
- app/controllers/ReportDeadlinesController.scala
- app/controllers/predicates/IncomeSourceDetailsPredicate.scala
- app/models/reportDeadlines/ReportDeadlinesResponseModel.scala
- app/services/IncomeSourceDetailsService.scala
- app/services/ReportDeadlinesService.scala
- test/assets/BaseTestConstants.scala
- test/audit/AuditingServiceSpec.scala
- test/audit/mocks/MockAuditingService.scala
- test/audit/models/ReportDeadlinesRequestAuditModelSpec.scala
- test/audit/models/ReportDeadlinesResponseAuditModelSpec.scala
- test/connectors/IncomeSourceDetailsConnectorSpec.scala
- test/connectors/ReportDeadlinesConnectorSpec.scala
- test/controllers/BillsControllerSpec.scala
- test/controllers/CalculationControllerSpec.scala
- test/controllers/EstimatesControllerSpec.scala
- test/controllers/ExitSurveyControllerSpec.scala
- test/controllers/predicates/NinoPredicateSpec.scala
- test/mocks/connectors/MockReportDeadlinesConnector.scala
- test/mocks/services/MockIncomeSourceDetailsService.scala
- test/mocks/services/MockReportDeadlinesService.scala
- test/services/IncomeSourceDetailsServiceSpec.scala
- test/services/NinoLookupServiceSpec.scala
- test/views/EstimatesViewSpec.scala
This is pending review by TxM.
> [BTAT-2186] Added AuditEvents for ReportDeadlines

- app/views/helpers/betaBanner.scala.html
- app/views/templates/govuk_wrapper.scala.html
- conf/messages
- conf/messages.cy
- test/views/helpers/BetaBannerHelperSpec.scala
I have also added the GA tag to the ITVC GA Confluence page
> BTAT-3414 Added custom beta banner and beta messages for both languages

- app/config/FrontendAppConfig.scala
Also removed the unused unauthenticated feedback URL.
> Added missing slash from start of beta feedback URL

- app/models/calculation/CalculationResponseModel.scala
- app/services/CalculationService.scala
- it/assets/CalcDataIntegrationTestConstants.scala
- it/controllers/CalculationControllerISpec.scala
- it/helpers/servicemocks/IncomeTaxViewChangeStub.scala
- test/assets/CalcBreakdownTestConstants.scala
- test/models/CalculationResponseModelSpec.scala
- test/services/CalculationServiceSpec.scala
Instead of calling calculation-store to get Calc Id replace that call with actual API 19A to get Calc Id to pass it to SA API.
Modified code and test to call the right api
> Mit 32R:Call api 19 a

- app/views/obligations.scala.html
- conf/messages
- conf/messages.cy
Before review the code, please change the app/controllers/ReportDeadlinesController.scala to obligation.sclala.html page
> MIT-178: Created dropdown content for declaration and quarterly return

- app/views/home.scala.html
- conf/messages
- conf/messages.cy
- test/views/HomePageViewSpec.scala
Confirm whether or not we use MTD-IT-ID or SA-UTR before merging.
> Added unique tax reference display onto home page for mtd it id.

- app/connectors/FinancialTransactionsConnector.scala
- app/connectors/IncomeTaxViewChangeConnector.scala
- app/connectors/UserDetailsConnector.scala
- app/controllers/BillsController.scala
- app/controllers/CalculationController.scala
- app/controllers/EstimatesController.scala
- app/models/calculation/CalculationResponseModel.scala
- app/services/CalculationService.scala
- it/controllers/BillsControllerISpec.scala
- it/controllers/EstimatesControllerISpec.scala
- it/controllers/HomeControllerISpec.scala
- it/helpers/servicemocks/IncomeTaxViewChangeStub.scala
- test/assets/EstimatesTestConstants.scala
- test/controllers/BillsControllerSpec.scala
- test/controllers/EstimatesControllerSpec.scala
- test/controllers/HomeControllerSpec.scala
- test/mocks/services/MockCalculationService.scala
- test/models/CalculationResponseModelSpec.scala
Updated checks on estimates controller to redirect if only one calculation is an uncrystallised calc model,
Removed some duplicate logging and unreachable code,
Updated and added tests
> Updated model so isError checks the status of the error model,

- app/auth/MtdItUser.scala
- app/config/FrontendAppConfig.scala
- app/connectors/PayApiConnector.scala
- app/controllers/PaymentController.scala
- app/controllers/predicates/AuthenticationPredicate.scala
- app/implicits/ImplicitJsonValidationFormatter.scala
- app/models/core/PaymentJourneyModel.scala
- app/views/crystallised.scala.html
- app/views/paymentDue.scala.html
- conf/application.conf
- it/assets/BaseIntegrationTestConstants.scala
- it/controllers/PaymentControllerISpec.scala
- it/helpers/ComponentSpecBase.scala
- it/helpers/WiremockHelper.scala
- it/helpers/servicemocks/AuthStub.scala
- it/helpers/servicemocks/IncomeTaxViewChangeStub.scala
- test/assets/BaseTestConstants.scala
- test/assets/Messages.scala
- test/assets/PaymentDataTestConstants.scala
- test/connectors/PayApiConnectorSpec.scala
- test/controllers/PaymentControllerSpec.scala
- test/controllers/predicates/NinoPredicateSpec.scala
- test/mocks/MockHttp.scala
- test/views/CrystallisedViewSpec.scala
- test/views/PaymentsDueViewSpec.scala
Merge AFTER:
https://github.com/hmrc/app-config-base/pull/2028
https://github.com/hmrc/service-manager-config/pull/1277
And the acceptance tests have been completed
> MIT 271 Create payments functionality

- app/connectors/IncomeTaxViewChangeConnector.scala
- app/controllers/PreviousObligationsController.scala
- app/models/reportDeadlines/ReportDeadlinesResponseModel.scala
- app/services/ReportDeadlinesService.scala
- app/views/home.scala.html
- app/views/obligations.scala.html
- app/views/previousObligations.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/assets/PreviousObligationsIntegrationTestConstants.scala
- it/assets/ReportDeadlinesIntegrationTestConstants.scala
- it/controllers/PreviousObligationsControllerISpec.scala
- it/helpers/ComponentSpecBase.scala
- it/helpers/servicemocks/IncomeTaxViewChangeStub.scala
- test/assets/Messages.scala
- test/assets/PropertyDetailsTestConstants.scala
- test/assets/ReportDeadlinesTestConstants.scala
- test/connectors/IncomeTaxViewChangeConnectorSpec.scala
- test/controllers/PreviousObligationsControllerSpec.scala
- test/mocks/connectors/MockIncomeTaxViewChangeConnector.scala
- test/mocks/services/MockReportDeadlinesService.scala
- test/services/ReportDeadlinesServiceSpec.scala
- test/views/HomePageViewSpec.scala
- test/views/ObligationsViewSpec.scala
- test/views/PreviousObligationsViewSpec.scala
- Updated home page to include a link to the new page.
- Updated obligations page with tabs to navigate between the current page and the new page.
- Created previous-obligations page
> Mit 227 - Added previous obligations page.

- app/views/helpers/calcBreakdownHelper.scala.html
- public/stylesheets/itvc.css
- test/views/CrystallisedViewSpec.scala
DAC requirement to change the calculation breakdown using a table into a grid layout.
> Updated the calculation breakdown to use grid system instead of tables

- app/views/paymentDue.scala.html
- conf/messages
- conf/messages.cy
- it/assets/messages/PaymentsDueMessages.scala
- it/controllers/PaymentDueControllerISpec.scala
- test/assets/MessagesLookUp.scala
- test/views/PaymentsDueViewSpec.scala
Content updated for Payments due page, breadcrumb,title updated
> MISUV-1233

- README.md
- app/controllers/HomeController.scala
- app/views/home.scala.html
- build.sbt
- conf/messages
- test/assets/MessagesLookUp.scala
- test/views/HomePageViewSpec.scala
Updated the Readme, Updated the dependancies, Added new section on homePage, Rebased for FS changes
> Updated the content on HomePage as per story/prototype,

- app/config/featureswitch/FeatureSwitch.scala
- conf/application.conf
> New feature switch added

- app/connectors/IndividualCalculationsConnector.scala
- app/models/calculation/Calculation.scala
- app/views/taxCalcBreakdown.scala.html
- conf/messages
- conf/messages.cy
- public/stylesheets/itvc.css
- test/assets/CalcBreakdownTestConstants.scala
- test/assets/MessagesLookUp.scala
- test/models/calculation/CalculationSpec.scala
- test/views/TaxCalcBreakdownViewSpec.scala
Special withholding tax,Void ISAs,Total income/NICs  tax due
Welsh updated
> New Minus Tax deducted at source data items added

- README.md
- app/views/agent/nextUpdates.scala.html
Amended tax years link on agent next updates page to redirect to tax years page.Updated the Readme
> Amended tax years link on agent next updates page to redirect to tax years page.

- app/config/FrontendAppConfig.scala
- app/controllers/agent/ClientRelationshipFailureController.scala
- app/controllers/agent/EnterClientsUTRController.scala
- app/controllers/agent/UTRErrorController.scala
- app/controllers/agent/predicates/BaseAgentController.scala
- app/controllers/errors/AgentErrorController.scala
- app/controllers/predicates/agent/AgentAuthenticationPredicate.scala
- app/views/errorPages/agentError.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages
- conf/messages.cy
- it/controllers/agent/EnterClientsUTRControllerISpec.scala
- it/controllers/errors/AgentErrorControllerISpec.scala
- test/assets/MessagesLookUp.scala
- test/controllers/agent/EnterClientsUTRControllerSpec.scala
- test/controllers/errors/AgentErrorControllerSpec.scala
- test/controllers/predicates/agent/AgentAuthenticationPredicateSpec.scala
- test/views/errorPages/AgentErrorViewSpec.scala
When a user without Agent Reference Number accesses the Enter Client's UTR page, then they are redirected to a new Not An Agent error page.
> MISUV-1462 Error page when a non agent tries to access the ITSA Viewer

- app/config/ItvcErrorHandler.scala
- app/controllers/DeductionsSummaryController.scala
- app/views/DeductionBreakdown.scala.html
- app/views/templates/ErrorTemplate.scala.html
- app/views/templates/GovUkWrapper.scala.html
- app/views/templates/MainTemplate.scala.html
- test/controllers/DeductionsSummaryControllerSpec.scala
- test/views/DeductionBreakdownViewSpec.scala
- injected helpers
- got rid of unused arguments in the view
- also processed main templates in the same way
> MISUV-1384 Migrated deductionBreakdown view to be injectable

- app/controllers/ChargeSummaryController.scala
- app/controllers/WhatYouOweController.scala
- app/controllers/agent/nextPaymentDue/PaymentDueController.scala
- app/services/WhatYouOweService.scala
- app/views/ChargeSummary.scala.html
- app/views/Home.scala.html
- app/views/WhatYouOwe.scala.html
- conf/app.routes
- it/controllers/WhatYouOweControllerISpec.scala
- test/controllers/WhatYouOweControllerSpec.scala
- test/controllers/agent/nextPaymentDue/PaymentDueControllerSpec.scala
- test/services/WhatYouOweServiceSpec.scala
- test/views/HomePageViewSpec.scala
- test/views/WhatYouOweViewSpec.scala
- Renamed Individual PaymentDueController to WhatYouOweController
> MISUV-2165 - Migrating WhatYouOwe view to be injectable

- app/auth/BaseFrontendController.scala
- app/models/calculation/Calculation.scala
- app/views/TaxCalcBreakdown.scala.html
- app/views/agent/TaxCalcBreakdown.scala.html
- conf/messages
- test/assets/CalcBreakdownTestConstants.scala
- test/assets/MessagesLookUp.scala
- test/models/calculation/CalculationSpec.scala
- test/views/TaxCalcBreakdownViewSpec.scala
Other charges section
- Underpaid tax for earlier years in your tax code for 2020 to 2021
- Underpaid tax for earlier years in your self assessment for 2020 to 2021 
Tax deductions section
- Outstanding debt collected through PAYE
> MISUV-2356 New Calc lines for Coding Out

- app/audit/models/PaymentAllocationsResponseAuditModel.scala
- app/audit/models/TaxYearOverviewResponseAuditModel.scala
- test/audit/models/PaymentAllocationsResponseAuditModelSpec.scala
- test/audit/models/TaxYearOverviewResponseAuditModelSpec.scala
Also fixes paymentallocationresponse audit message description
> Misuv 2473 Add Tax Year Overview Late Payment Details to Audit Events

- app/views/BtaPartial.scala.html
- app/views/ChargeSummary.scala.html
- app/views/Home.scala.html
- app/views/NextUpdates.scala.html
- app/views/NoNextUpdates.scala.html
- app/views/PaymentAllocation.scala.html
- app/views/PaymentHistory.scala.html
- app/views/WhatYouOwe.scala.html
- app/views/agent/ClientRelationshipFailure.scala.html
- app/views/agent/Home.scala.html
- app/views/agent/UTRError.scala.html
- app/views/agent/confirmClient.scala.html
- app/views/components/home_tile.scala.html
- app/views/errorPages/AgentError.scala.html
- app/views/errorPages/StandardError.scala.html
- app/views/errorPages/UpliftFailed.scala.html
- app/views/layouts/agent/layout.scala.html
- app/views/layouts/agent/mainContentTemplate.scala.html
- app/views/timeout/Timeout.scala.html
- it/controllers/agent/HomeControllerISpec.scala
- public/stylesheets/itvc_custom.css
- test/views/agent/HomePageViewSpec.scala
Includes refactoring p component to be more consistent with standard play formatting and improve usability when dealing with larger html snippets.
> MISUV-2392 Migrated agent homepage to hmrc-frontend.

- app/models/financialDetails/DocumentDetail.scala
- app/views/ChargeSummary.scala.html
- app/views/WhatYouOwe.scala.html
- conf/messages
- it/controllers/ChargeSummaryControllerISpec.scala
- test/testConstants/FinancialDetailsTestConstants.scala
- test/views/ChargeSummaryViewSpec.scala
- test/views/WhatYouOweViewSpec.scala
Added Coding Out details to Charge Summary page (linked from whatyouowe page)
> Misuv 2655 coding out sa page

- app/views/TaxYearOverview.scala.html
- app/views/TaxYears.scala.html
- app/views/agent/TaxYearOverview.scala.html
- app/views/partials/paymentAllocations/agent/AgentPaymentAllocationsForNonLpi.scala.html
- app/views/partials/taxOverviewBreakdownPartial.scala.html
- it/controllers/TaxYearOverviewControllerISpec.scala
- it/controllers/agent/TaxYearOverviewControllerISpec.scala
- it/testConstants/messages/TaxYearOverviewMessages.scala
- test/views/TaxYearOverviewViewSpec.scala
- test/views/agent/TaxYearOverviewViewSpec.scala
Replacement for pull request https://github.com/hmrc/income-tax-view-change-frontend/pull/945 due to unverified commits.
> Migrated TaxYearOverview page, associated tests and misc. files.

- app/views/FinalTaxCalculationView.scala.html
- conf/messages
- conf/messages.cy
- it/controllers/FinalTaxCalculationControllerISpec.scala
- it/controllers/agent/FinalTaxCalculationControllerISpec.scala
Linked to [Income Tax Submission Frontend](https://github.com/hmrc/income-tax-submission-frontend/pull/170)
> SASS-1488 : added welsh translation for final tax overview page

- conf/messages.cy
- test/testConstants/BusinessDetailsTestConstants.scala
- test/views/NextUpdatesViewSpec.scala
- test/views/agent/NextUpdatesViewSpec.scala
- test/views/html/helpers/injected/obligations/NextUpdatesHelperSpec.scala
- test/views/obligationTemplates/NextUpdatesHelperSpec.scala
Add Welsh text for nextUpdates.business message
> MISUV-2856 Add missing welsh content on the 'Next Updates' page

- app/controllers/agent/HomeController.scala
- test/controllers/agent/HomeControllerSpec.scala
Bug fix for not showing Due Payments warning on Home page when logged as an Agent
> MISUV-2872 Fix the bug with overdue warning message is not appearing

- app/views/ForecastIncomeSummary.scala.html
> MISUV-3540 fixed spacing ForecastIncomeSummary.scala.html

- app/views/PaymentHistory.scala.html
- test/views/PaymentHistoryViewSpec.scala
* update the order of entries in PaymentHistory: earliest first order
> MISUV-3671: update the order of entries in PaymentHistory

- app/controllers/HomeController.scala
- app/controllers/NotMigratedUserController.scala
- app/views/Home.scala.html
- app/views/notMigrated/NotMigratedUser.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- test/controllers/NotMigratedUserControllerSpec.scala
- test/mocks/services/MockIncomeSourceDetailsService.scala
- test/testConstants/IncomeSourceDetailsTestConstants.scala
- test/views/HomePageViewSpec.scala
* create new controller and view for not migrated users;
* add new routes as required;
* added controller unit test;
> MISUV-3710: create required view / controller

- app/views/notMigrated/NotMigratedUser.scala.html
* minor style fix to align UI with what is in the prototype;
> MISUV-3710: minor style fix

- conf/messages
- conf/messages.cy
* fix duplicate text in the link
> MISUV-3710: fix duplicate text in the link

- app/views/CreditAndRefunds.scala.html
Added dd element to the list for accessibility test
> MISUV-3718: Claim a Refund page 

- app/views/CreditAndRefunds.scala.html
- test/views/CreditAndRefundsViewSpec.scala
Fix for Accessibility issues and updated tests
> MISUV-3718 Update Claim a Refund 

- app/views/agent/ClientRelationshipFailure.scala.html
- conf/agent.routes
- conf/messages
- conf/messages.cy
- it/helpers/agent/ComponentSpecBase.scala
- test/views/agent/ClientDetailsFailureViewSpec.scala
* update ClientRelationshipFailureController routing mapping;
> MISUV-3770: update content 'Error Pages  - the client-agent relationship not found'

- test/views/helpers/RadioOptionSpec.scala
> MISUV-3633: improve test coverage / RadioOption

- app/controllers/CreditAndRefundController.scala
- app/views/CreditAndRefunds.scala.html
- it/controllers/CreditAndRefundControllerISpec.scala
Reverts hmrc/income-tax-view-change-frontend#1379
> Revert "Misuv 3828 display 'credit from an earlier tax year' (cutover credits) label in claim a refund page"

- test/models/helpers/LiabilityCalculationDataHelper.scala
- test/models/liabilitycalculation/LiabilityCalculationResponseModelSpec.scala
> MISUV-3647: improve test coverage

- test/controllers/NextUpdatesControllerSpec.scala
- test/mocks/services/MockIncomeSourceDetailsService.scala
> MISUV-3990: improve test coverage / IncomeSourceDetailsPredicateNoCache

- test/controllers/predicates/AuthPredicateSpec.scala
- test/controllers/predicates/AuthenticationPredicateSpec.scala
> MISUV-3985: AuthPredicate / improve test coverage

- app/views/CreditAndRefunds.scala.html
- it/controllers/CreditAndRefundControllerISpec.scala
- it/controllers/agent/CreditAndRefundControllerISpec.scala
* Only relevant integration tests updated at this stage;
* id attribute added to relevant <a> element to help located element on the page;
> MISUV-4018: add missing integration tests

- app/connectors/RepaymentConnector.scala
- app/controllers/CreditAndRefundController.scala
- app/services/RepaymentService.scala
- app/views/CreditAndRefunds.scala.html
- conf/app.routes
- conf/application.conf
- test/connectors/RepaymentConnectorSpec.scala
- test/controllers/CreditAndRefundControllerSpec.scala
* add RepaymentService : required tests in TODO;
* update logic to request refund and refund status;
* Still in TODO: check refund status;
> MISUV-4602: step one: enable refund link

- it/helpers/CreditsSummaryDataHelper.scala
* fix failing IT tests[attempt - 2]: ~data field expected to be dynamic;
> MISUV-4694: fix failing IT tests

- app/config/featureswitch/FeatureSwitch.scala
- app/controllers/IncomeSummaryController.scala
- app/models/liabilitycalculation/viewmodels/IncomeBreakdownViewModel.scala
- test/controllers/IncomeSummaryControllerSpec.scala
- test/models/liabilitycalculation/viewmodels/IncomeBreakdownViewModelSpec.scala
> MISUV-4742 - Removed New State Benefit from Feature Switch.

- app/connectors/RepaymentConnector.scala
- app/models/core/Nino.scala
- conf/application.conf
- test/connectors/RepaymentConnectorSpec.scala
* Fix invalid Json issue; 
* ** TODO:fix broken unit tests;
> MISUV-4714: Fix invalid Json issue

- app/views/RefundToTaxPayer.scala.html
- conf/messages
- conf/messages.cy
Fixed wrapping of date in Welsh
> MISUV-4880 - Updated 'Estimated date' field name in Refund to taxpayer page

- app/controllers/predicates/AuthenticationPredicate.scala
- it/controllers/HomeControllerISpec.scala
- it/helpers/servicemocks/AuthStub.scala
- test/controllers/predicates/AuthenticationPredicateSpec.scala
- test/views/RefundToTaxPayerViewSpec.scala
Fixes IV Uplift url bug in prod
> Misuv 4911 prod id verification url

- app/testOnly/connectors/DynamicStubConnector.scala
- app/testOnly/controllers/StubSchemaController.scala
- app/utils/SessionBuilder.scala
- conf/testOnlyDoNotUseInAppConf.routes
* enable custom login page on the staging;
> MISUV-4823: enable custom login page

- app/testOnly/controllers/StubSchemaController.scala
> MISUV-4823: fix agents login page

- app/audit/AuditingService.scala
- test/audit/AuditServiceSpec.scala
Removed obsolete test and moved private logic into public methods for better logging
> MISUV 4414: Investigate: AuditServiceSpec re-enable disabled unit test

- app/config/featureswitch/FeatureSwitch.scala
- app/controllers/CreditAndRefundController.scala
- app/controllers/CreditsSummaryController.scala
- app/controllers/RefundToTaxPayerController.scala
- it/controllers/CreditAndRefundControllerISpec.scala
- it/controllers/CreditsSummaryControllerISpec.scala
- it/controllers/RefundToTaxPayerControllerISpec.scala
- it/controllers/agent/CreditAndRefundControllerISpec.scala
- test/controllers/RefundToTaxPayerControllerSpec.scala
DONT MERGE
--------
ATs failing, in touch with Joshua.
> MISUV-5079 - Remove R7C Feature Switch

- app/models/financialDetails/FinancialDetailsResponseModel.scala
- app/services/WhatYouOweService.scala
- test/models/FinancialDetailsResponseModelSpec.scala
- test/services/WhatYouOweServiceSpec.scala
Implemented new logic for method and changed both calls, also changed the tests for new datatype
> Misuv 5012: FinancialDetailsModel and WhatYouOweService: fix validChargeTypeCondition

- app/connectors/IncomeTaxViewChangeConnector.scala
- app/models/repaymentHistory/RepaymentHistoryUtils.scala
> MISUV-5082 Prod Bug Missing DueDate in Payments list - Logger level to WARN.

- app/audit/models/ClaimARefundAuditModel.scala
- app/controllers/CreditAndRefundController.scala
- app/models/financialDetails/FinancialDetail.scala
- app/services/CreditHistoryService.scala
- app/utils/CreditAndRefundUtils.scala
- app/views/CreditAndRefunds.scala.html
- test/models/financialDetails/FinancialDetailSpec.scala
Replaced old Boolean methods with single getCreditType: Option[String] method. Replaced all calls to old methods with call to new method. Added tests for new method
> Misuv 5128: FE: refactor FinancialDetail : extract getCreditType method

- app/views/WhatYouOwe.scala.html
- it/controllers/WhatYouOweControllerISpec.scala
- test/views/WhatYouOweViewSpec.scala
> MISUV-5248 HMRC adjustment - possible accessibility issue with this label

- project/plugins.sbt
> MISUV-5131: failing build

- project/plugins.sbt
- test/config/featureswitch/FeatureSwitchingSpec.scala
* rollback changes from first attempt;
* simulating build failure[2] - breaking changes in the test
> MISUV-5131: simulate build failure v2

- test/config/featureswitch/FeatureSwitchingSpec.scala
> MISUV-5131: revet build failure simulation changes

- it/controllers/InYearTaxCalculationControllerISpec.scala
* final unit tests fixes for new taxYear switch;
> MISUV-5357: final fixes

- app/views/ChargeSummary.scala.html
- test/views/ChargeSummaryViewSpec.scala
added toStrings to necessary places on Charge Summary page
> MISUV-5429 - Fix tax year message on Charge summary page

- app/controllers/HomeController.scala
- app/services/WhatYouOweService.scala
> MISUV-5431: code refactoring

- app/controllers/AddIncomeSourceController.scala
- app/services/IncomeSourceDetailsService.scala
- test/controllers/AddIncomeSourceControllerSpec.scala
- test/services/IncomeSourceDetailsServiceSpec.scala
- test/testConstants/BusinessDetailsTestConstants.scala
- test/testConstants/IncomeSourceDetailsTestConstants.scala
- test/testConstants/PropertyDetailsTestConstants.scala
* improve error handling: IncomeSourceDetailsService.AddIncomeSourcesViewModel method;
* fix relevant broken tests;
> MISUV-5530: add error logging 

- app/connectors/AddressLookupConnector.scala
- app/services/AddressLookupService.scala
> MISUV-5104: fix

- test/forms/incomeSources/add/ForeignPropertyStartDateFormSpec.scala
> MISUV-5768: fix failing build

- app/connectors/AddressLookupConnector.scala
> MISUV-5188: fix addressLookup v3

- app/controllers/incomeSources/add/CheckBusinessDetailsController.scala
- app/views/incomeSources/add/CheckBusinessDetails.scala.html
- conf/messages.cy
Hot fix for session log out issues
> MISUV-5735-fix - update welsh title and spacing

- app/views/incomeSources/add/BusinessAddedObligations.scala.html
Changed the html for the green banner to reflect better html practices
> MISUV-5664-Banner-Fix

- app/controllers/incomeSources/add/ForeignPropertyReportingMethodController.scala
* code refactoring as requested
> MISUV-5872: error handling enhancements 

- app/models/incomeSourceDetails/viewmodels/ObligationsViewModel.scala
- app/services/NextUpdatesService.scala
- it/controllers/agent/incomeSources/manage/ManageObligationsControllerISpec.scala
- it/controllers/incomeSources/manage/ManageObligationsControllerISpec.scala
- it/testConstants/IncomeSourcesObligationsIntegrationTestConstants.scala
- test/audit/models/ObligationsAuditModelSpec.scala
- test/controllers/incomeSources/add/IncomeSourceAddedControllerSpec.scala
- test/controllers/incomeSources/manage/ManageObligationsControllerSpec.scala
- test/services/NextUpdatesServiceSpec.scala
- test/testConstants/incomeSources/IncomeSourcesObligationsTestConstants.scala
- test/views/incomeSources/add/IncomeSourceAddedObligationsViewSpec.scala
- test/views/incomeSources/cease/IncomeSourceCeasedObligationsViewSpec.scala
- test/views/incomeSources/manage/ManageObligationsViewSpec.scala
* initial change to drop defaults in model DatesModel;
> MISUV-6494: remove defaults in model DatesModel 

- app/audit/models/IncomeSourceReportingMethodAuditModel.scala
- app/controllers/incomeSources/add/BusinessReportingMethodController.scala
- app/controllers/incomeSources/add/ForeignPropertyReportingMethodController.scala
- app/controllers/incomeSources/add/UKPropertyReportingMethodController.scala
- app/controllers/incomeSources/manage/ConfirmReportingMethodSharedController.scala
- app/enums/AuditType/AuditType.scala
- app/enums/TransactionName/TransactionName.scala
- app/models/incomeSourceDetails/IncomeSourceDetailsResponse.scala
- it/controllers/agent/incomeSources/add/BusinessReportingMethodControllerISpec.scala
- it/controllers/agent/incomeSources/add/ForeignPropertyReportingMethodControllerISpec.scala
- it/controllers/agent/incomeSources/add/UKPropertyReportingMethodControllerISpec.scala
- it/controllers/agent/incomeSources/manage/ConfirmReportingMethodSharedControllerISpec.scala
- it/controllers/incomeSources/add/BusinessReportingMethodControllerISpec.scala
- it/controllers/incomeSources/add/ForeignPropertyReportingMethodControllerISpec.scala
- it/controllers/incomeSources/add/UKPropertyReportingMethodControllerISpec.scala
- it/controllers/incomeSources/manage/ConfirmReportingMethodSharedControllerISpec.scala
- test/controllers/incomeSources/add/BusinessReportingMethodControllerSpec.scala
- test/controllers/incomeSources/add/ForeignPropertyReportingMethodControllerSpec.scala
- test/controllers/incomeSources/add/UKPropertyReportingMethodControllerSpec.scala
- test/controllers/incomeSources/manage/ConfirmReportingMethodSharedControllerSpec.scala
SCP025 | Add&Manage SE & Property | TxM event - Update Income Source: success/failure (API#1776)
> MISUV-6561 SCP025 | Add&Manage SE & Property | TxM event - Update Income Source: success/failure (API#1776)

- app/controllers/incomeSources/add/IncomeSourceCheckDetailsController.scala
- app/controllers/incomeSources/cease/IncomeSourceCeasedObligationsController.scala
* yet another attempt to detect BoxedError in QA;
> MISUV-6574: BoxedError 

- app/controllers/incomeSources/cease/IncomeSourceCeasedObligationsController.scala
- test/controllers/incomeSources/cease/IncomeSourceCeasedObligationsControllerSpec.scala
* fix issue with Obligations in Ceased Property page;
> MISUV-6574: QA env fix 

- app/models/incomeSourceDetails/PropertyDetailsModel.scala
- test/controllers/incomeSources/cease/IncomeSourceCeasedObligationsControllerSpec.scala
> MISUV-6631: code tidy up

- app/services/NextUpdatesService.scala
* attempt to fix duplication in obligations in Tax-Year-Summary page: issue raised during E2E testing;
> MISUV-6666: remove obligations duplications

- app/services/NextUpdatesService.scala
- app/views/TaxYearSummary.scala.html
* remove obligations duplication on the view level;
* remove distinct usage on the level of service;
> MISUV-6666: remove obligations duplications in TaxYearSummary page 

- app/models/liabilitycalculation/LiabilityCalculationResponse.scala
- conf/messages
- conf/messages.cy
- test/views/TaxCalcBreakdownViewSpec.scala
…tions page with info messages (dev ticket)
> MISUV-6620 PBM007 - Basic rate divergence| Build - Update Tax calculations page with info messages (dev ticket)

- test/audit/models/WhatYouOweResponseAuditModelSpec.scala
* replace LocalDate.now with fixed date;
> MISUV-6855: Set fixed date 

- project/plugins.sbt
- test/audit/models/WhatYouOweResponseAuditModelSpec.scala
- test/controllers/incomeSources/add/AddIncomeSourceStartDateCheckControllerSpec.scala
- test/mocks/connectors/MockFinancialDetailsConnector.scala
- test/services/FinancialDetailsServiceSpec.scala
- test/services/NextUpdatesServiceSpec.scala
- test/services/WhatYouOweServiceSpec.scala
- test/testConstants/BusinessDetailsTestConstants.scala
- test/testConstants/FinancialDetailsTestConstants.scala
- test/testUtils/TestSupport.scala
- test/views/WhatYouOweViewSpec.scala
* set valid fixedDate day[3];
* remove LocalDate.now usages
[Remaining usages of LocalDate.now to be investigate ](https://jira.tools.tax.service.gov.uk/browse/MISUV-6871)
* upgrade sbt-auto-build to recent~ version;
> MISUV-6855: enable disabled test in WhatYouOweResponseAuditModelSpec & other related changes 

- test/services/helpers/ActivePropertyBusinessesHelperSpec.scala
* change how we compare Left result
Please refer to next documentation for more details: 
https://www.scalatest.org/user_guide/using_EitherValues
> MISUV-5897: code tidy up

- test/models/WhatYouOweChargesListModelSpec.scala
*  fix failing tests: replace LocalDate.now with a fixedDate;
> Fix failing build

- app/audit/models/ForecastIncomeAuditModel.scala
*remove allOtherIncomeType var;
> MISUV-6900: var removal from  app/audit/models/ForecastIncomeAuditModel.scala

- test/config/featureswitch/FeatureSwitchingSpec.scala
> MISUV-6900: Patch

- app/controllers/incomeSources/add/AddIncomeSourceStartDateController.scala
- app/forms/incomeSources/add/AddIncomeSourceStartDateForm.scala
- test/forms/incomeSources/add/AddIncomeSourceStartDateFormSpec.scala
- test/views/WhatYouOweViewSpec.scala
> MISUV-7028: Update -Business start date in future - error message

- build.sbt
* final fix: resolve issue when run sbt it/clean sbt it/compile
> MISUV-6988: final fix

- app/controllers/agent/EnterClientsUTRController.scala
- app/services/agent/ClientDetailsService.scala
- it/test/controllers/agent/EnterClientsUTRControllerISpec.scala
- test/controllers/agent/EnterClientsUTRControllerSpec.scala
- test/services/agent/ClientDetailsServiceSpec.scala
Changed 'UnexpectedError' to 'APIError' and handled the exception gracefully, rather than throwing it in FE
> MISUV-7093 Citizen Details logging

- app/models/repaymentHistory/RepaymentHistory.scala
- app/models/repaymentHistory/RepaymentHistoryUtils.scala
- it/test/controllers/RefundToTaxPayerControllerISpec.scala
- test/audit/models/RefundToTaxPayerResponseAuditModelSpec.scala
- test/controllers/RefundToTaxPayerControllerSpec.scala
- test/models/repaymentHistory/RepaymentHistoryAggSpec.scala
- test/models/repaymentHistory/RepaymentHistorySpec.scala
- test/models/repaymentHistory/RepaymentHistoryUtilsSpec.scala
- test/testConstants/RepaymentHistoryTestConstants.scala
- test/views/RefundToTaxPayerViewSpec.scala
MISUV-7194: added filter for approved repayments.
>  MISUV-7081: Refunds having status of 'Approved' to be displayed on history page

- app/views/manageBusinesses/add/AddProperty.scala.html
- test/forms/incomeSources/add/AddPropertyFormSpec.scala
Added tests for AppPropertyView and moved the red error line logic into a neater function in AddPropertyView
> MISUV-7219 Form tests and view refactor

- app/assets/stylesheets/application.scss
- app/views/layouts/unifiedLayout.scala.html
- app/views/navBar/BtaNavBar.scala.html
- test/views/ChargeSummaryViewSpec.scala
> MISUV-7263 - Staging Account header update - remove logo

- app/models/liabilitycalculation/viewmodels/TaxDueSummaryViewModel.scala
- app/views/TaxCalcBreakdown.scala.html
- test/models/liabilitycalculation/viewmodels/TaxDueSummaryViewModelSpec.scala
- test/views/TaxCalcBreakdownViewSpec.scala
MISUV-7258: transitional profit - improved code readability
- moved logic to view model
> MISUV-7258: transitional profit - improved code readability

- it/test/controllers/CreditsSummaryControllerISpec.scala
- it/test/helpers/CreditsSummaryDataHelper.scala
- test/audit/models/ChargeSummaryAuditSpec.scala
- test/audit/models/TaxYearSummaryResponseAuditModelSpec.scala
- test/models/repaymentHistory/RepaymentHistoryAggSpec.scala
- test/views/ChargeSummaryViewSpec.scala
All LocalDate.now() from unit and it/test replaced with fixedDate
> MISUV-6871_v2: Investigate: LocalDate.now removal from unit tests and it:Tests 

- app/views/helpers/injected/BackLinkWithFallback.scala.html
- app/views/layouts/unifiedLayout.scala.html
- it/test/controllers/agent/manageBusinesses/ManageYourBusinessesControllerISpec.scala
- it/test/controllers/agent/manageBusinesses/manage/ManageIncomeSourceControllerISpec.scala
- it/test/controllers/incomeSources/manage/ManageIncomeSourceControllerISpec.scala
- it/test/controllers/manageBusinesses/ManageYourBusinessesControllerISpec.scala
- it/test/controllers/manageBusinesses/manage/ManageIncomeSourceControllerISpec.scala
- test/controllers/incomeSources/add/AddIncomeSourceStartDateCheckControllerSpec.scala
- test/controllers/incomeSources/add/AddIncomeSourceStartDateControllerSpec.scala
- test/controllers/incomeSources/cease/IncomeSourceEndDateControllerSpec.scala
- test/controllers/manageBusinesses/add/AddIncomeSourceStartDateCheckControllerSpec.scala
- test/controllers/manageBusinesses/add/AddIncomeSourceStartDateControllerSpec.scala
- test/controllers/manageBusinesses/cease/IncomeSourceEndDateControllerSpec.scala
- test/views/incomeSources/add/AddIncomeSourceStartDateCheckViewSpec.scala
- test/views/incomeSources/add/AddIncomeSourceStartDateViewSpec.scala
- test/views/incomeSources/cease/DeclarePropertyCeasedViewSpec.scala
- test/views/incomeSources/cease/IncomeSourceEndDateViewSpec.scala
- test/views/incomeSources/manage/ConfirmReportingMethodSharedControllerViewSpec.scala
- test/views/incomeSources/manage/ManageIncomeSourceDetailsViewSpec.scala
- test/views/manageBusinesses/add/AddIncomeSourceStartDateCheckViewSpec.scala
- test/views/manageBusinesses/add/AddIncomeSourceStartDateViewSpec.scala
- test/views/manageBusinesses/cease/DeclarePropertyCeasedViewSpec.scala
- test/views/manageBusinesses/cease/IncomeSourceEndDateViewSpec.scala
- test/views/manageBusinesses/manage/ConfirmReportingMethodSharedControllerViewSpec.scala
- test/views/manageBusinesses/manage/ManageIncomeSourceDetailsViewSpec.scala
changed useFallbackBackLink default to true. Amended the test cases.
> MISUV-5754: changed useFallbackBackLink default to true. amended the test cases

- app/connectors/FinancialDetailsConnector.scala
- app/controllers/ChargeSummaryController.scala
- app/services/FinancialDetailsService.scala
Tidying up logs that were made whilst investigating MISUV 7208
> MISUV-7208-revert-obsolete-loggers-and-clean-overall

- app/controllers/manageBusinesses/add/IncomeSourcesAccountingMethodController.scala
- app/enums/IncomeSourceJourney/IncomeSourceType.scala
- app/forms/incomeSources/add/IncomeSourcesAccountingMethodForm.scala
- app/forms/incomeSources/cease/IncomeSourceEndDateForm.scala
- app/views/manageBusinesses/add/IncomeSourcesAccountingMethod.scala.html
- app/views/manageBusinesses/cease/IncomeSourceEndDate.scala.html
- conf/messages
- conf/messages.cy
- it/test/controllers/agent/manageBusinesses/cease/IncomeSourceEndDateControllerISpec.scala
- it/test/controllers/manageBusinesses/cease/IncomeSourceEndDateControllerISpec.scala
- test/forms/incomeSources/add/IncomeSourcesAccountingMethodFormSpec.scala
- test/forms/incomeSources/cease/IncomeSourceEndDateFormSpec.scala
- test/testConstants/PropertyDetailsTestConstants.scala
- test/testConstants/incomeSources/IncomeSourceDetailsTestConstants.scala
- test/views/manageBusinesses/add/IncomeSourcesAccountingMethodViewSpec.scala
- test/views/manageBusinesses/cease/IncomeSourceEndDateViewSpec.scala
[MISUV-7305](https://jira.tools.tax.service.gov.uk/browse/MISUV-7305)
SCP025&SCP001 | New journey content changes: Business accounting method page; Date your business stopped
> MISUV-7331-cease-new-content-accounting-method-date-stopped

- app/connectors/FeedbackConnector.scala
- it/test/controllers/agent/FeedbackControllerISpec.scala
- it/test/controllers/feedback/FeedbackControllerISpec.scala
- test/connectors/FeedbackConnectorSpec.scala
- test/controllers/FeedbackControllerSpec.scala
unit tests for controller getting null
> MISUV-5613: Unit tests for FeedbackController

- app/config/FrontendAppConfig.scala
- app/testOnly/TestOnlyAppConfig.scala
- app/testOnly/connectors/SessionDataConnector.scala
moved session-data url from testOnlyAppConfig to TestOnlyAppConfig
> MISUV-7408-appconfig

- app/config/featureswitch/FeatureSwitch.scala
Created FS to begin work on the development of the Claim to Adjust POA journey
> MISUV-7474-create-CTA-FS

- app/connectors/CalculationListConnector.scala
- app/controllers/WhatYouOweController.scala
- app/models/nextPayments/viewmodels/WYOClaimToAdjustViewModel.scala
- app/services/CalculationListService.scala
- app/services/ClaimToAdjustService.scala
- app/services/DateService.scala
- app/services/WhatYouOweService.scala
- app/views/WhatYouOwe.scala.html
- it/test/controllers/WhatYouOweControllerISpec.scala
- it/test/helpers/ComponentSpecBase.scala
- it/test/helpers/agent/ComponentSpecBase.scala
- test/controllers/WhatYouOweControllerSpec.scala
- test/forms/IncomeSourcesFormsSpec.scala
- test/models/incomeSourceDetails/viewmodels/IncomeSourceCeasedObligationsViewModelSpec.scala
- test/services/ClaimToAdjustPOA/ClaimToAdjustServiceSpec.scala
- test/views/NextUpdatesViewSpec.scala
- test/views/PaymentHistoryViewSpec.scala
- test/views/TaxYearSummaryViewSpec.scala
- test/views/WhatYouOweViewSpec.scala
[MISUV-7388](https://jira.tools.tax.service.gov.uk/browse/MISUV-7388) working on the visible aspects of this ticket, aka including the links to the new page in the correct places
> MISUV-7475-fe-work-claim-to-adjust-entry-point

- app/audit/models/ChargeSummaryAudit.scala
- app/controllers/ChargeSummaryController.scala
- app/models/chargeSummary/PaymentHistoryAllocation.scala
- app/models/financialDetails/CreditType.scala
- app/models/financialDetails/FinancialDetail.scala
- app/models/financialDetails/FinancialDetailsResponseModel.scala
- app/models/financialDetails/PaymentsResponse.scala
- app/models/financialDetails/SubItem.scala
- app/services/WhatYouOweService.scala
- app/views/ChargeSummary.scala.html
- app/views/partials/chargeSummary/ChargeSummaryHasPaymentBreakdown.scala.html
- app/views/partials/chargeSummary/ChargeSummaryPaymentAllocation.scala.html
- it/test/controllers/ChargeSummaryControllerISpec.scala
- it/test/controllers/agent/ChargeSummaryControllerISpec.scala
- it/test/testConstants/IncomeSourceIntegrationTestConstants.scala
- test/audit/models/ChargeSummaryAuditSpec.scala
- test/controllers/ChargeSummaryControllerSpec.scala
- test/models/FinancialDetailsResponseModelSpec.scala
- test/models/PaymentsAllocationChargesModelSpec.scala
- test/services/helpers/CreditHistoryDataHelper.scala
- test/testConstants/FinancialDetailsTestConstants.scala
- test/testConstants/PaymentAllocationsTestConstants.scala
- test/views/ChargeSummaryViewSpec.scala
* create replicate of original branch;
> MISUV-7407: branch copy

- app/controllers/ChargeSummaryController.scala
- app/views/ChargeSummary.scala.html
- it/test/controllers/ChargeSummaryControllerISpec.scala
- it/test/testConstants/IncomeSourceIntegrationTestConstants.scala
- test/controllers/ChargeSummaryControllerTest.scala
MISUV-7493: remove exceptions from view, validate values in controller
> remove exceptions from view, validate values in controller

- test/connectors/AddressLookupConnectorSpec.scala
- test/connectors/BusinessDetailsConnectorSpec.scala
- test/connectors/CalculationListConnectorSpec.scala
- test/connectors/CitizenDetailsConnectorSpec.scala
- test/connectors/CreateIncomeSourcesConnectorSpec.scala
- test/connectors/FeedbackConnectorSpec.scala
- test/connectors/FinancialDetailsConnectorSpec.scala
- test/connectors/ITSAStatusConnectorSpec.scala
- test/connectors/IncomeTaxCalculationConnectorSpec.scala
- test/connectors/ObligationsConnectorSpec.scala
- test/connectors/PayApiConnectorSpec.scala
- test/connectors/RepaymentConnectorSpec.scala
- test/connectors/RepaymentHistoryConnectorSpec.scala
- test/connectors/UpdateIncomeSourceConnectorSpec.scala
- test/mocks/MockHttp.scala
> ITVC-FE: Refactor PR

- app/config/featureswitch/FeatureSwitch.scala
- app/controllers/predicates/AuthenticationPredicate.scala
- test/controllers/predicates/AuthenticationPredicateSpec.scala
There is not plan to use this FS in the future, will be always set to true;
also this will simplify implementing read FS from mongo;
> MISUV-7618: decommission IvUplift FS

- app/controllers/NextUpdatesController.scala
- app/services/optout/OptOutService.scala
- test/services/optout/OptOutServiceTest.scala
Removes the use of toF(), since we want to get a deeper understanding of this approach before bringing it into the codebase.
> Misuv 7542 4 refactor opt out for comprehensions

- app/config/featureswitch/FeatureSwitching.scala
- app/controllers/ForecastIncomeSummaryController.scala
- app/controllers/ForecastTaxCalcSummaryController.scala
- app/controllers/predicates/NavBarFromNinoPredicate.scala
- app/models/admin/FeatureSwitchName.scala
- conf/application.conf
- test/config/featureswitch/FeatureSwitchingSpec.scala
- test/controllers/ForecastIncomeSummaryControllerSpec.scala
- test/controllers/ForecastTaxCalcSummaryControllerSpec.scala
- test/controllers/predicates/NavBarFromNinoPredicateSpec.scala
* patch NavBarFromNinoPredicate: load FS state from mongo fix;
* mark isDisabled method as deprecated;
> MISUV-5195: NavBarPredicate patch

- app/services/optout/OptOutTaxYear.scala
small change: improve boolean check
> MISUV-7623-OneYear

- app/connectors/optout/ITSAStatusUpdateConnector.scala
- test/connectors/optout/ITSAStatusUpdateConnectorTest.scala
- test/services/optout/OptOutTestSupport.scala
- test/services/optout/optoutproposition/OptOutPropositionYearsToOfferSpec.scala
- test/services/optout/optoutproposition/OptOutPropositionYearsToUpdateSpec.scala
use correct tax-year format for request
> use correct tax-year format for request

- app/connectors/optout/ITSAStatusUpdateConnector.scala
- app/connectors/optout/OptOutUpdateRequestModel.scala
- it/test/helpers/ITSAStatusUpdateConnectorStub.scala
> adjust api call url

- app/connectors/ClaimToAdjustPoaConnector.scala
- app/views/claimToAdjustPoa/ConfirmationForAdjustingPoa.scala.html
- it/test/connectors/ClaimToAdjustPoaConnectorSpec.scala
- it/test/helpers/servicemocks/IncomeTaxViewChangeStub.scala
added itvc prefix to url, and added support for post request
> MISUV-7719-intercept-poa-post

- app/controllers/DeductionsSummaryController.scala
- app/controllers/TaxYearSummaryController.scala
- app/services/ClaimToAdjustService.scala
- app/services/admin/FeatureSwitchService.scala
- app/testOnly/services/OptOutCustomDataService.scala
remove [class][method] from log statements
> remove [class][method] from log statements

- app/controllers/claimToAdjustPoa/ConfirmationForAdjustingPoaController.scala
- app/services/ClaimToAdjustPoaCalculationService.scala
- test/controllers/claimToAdjustPoa/ConfirmationForAdjustingPoaControllerSpec.scala
- test/mocks/connectors/MockClaimToAdjustPoaConnector.scala
- test/mocks/services/MockClaimToAdjustPoaCalculationService.scala
- test/services/claimToAdjust/ClaimToAdjustPoaCalculationServiceSpec.scala
> MISUV-7647: Claim to Adjust POA | Build - Declaration for adjusting POA page - UTs

- app/controllers/ChargeSummaryController.scala
- test/controllers/ChargeSummaryControllerSpec.scala
- test/controllers/ChargeSummaryControllerTest.scala
* - fix FS bug in ChargeSummaryController / STAGING specific;
* - fix UT;
> MISUV-7256: patch/2 - FS not extracted from MongoDb  for ChargeSummaryController =>

- test/services/claimToAdjust/ClaimToAdjustPoaCalculationServiceSpec.scala
Changed whenReady to futureValue
> MISUV-7647: Small change

- app/controllers/ChargeSummaryController.scala
- app/controllers/FinalTaxCalculationController.scala
- app/controllers/TaxYearSummaryController.scala
- app/controllers/feedback/FeedbackController.scala
- app/utils/AuthenticatorPredicate.scala
- test/controllers/FeedbackControllerSpec.scala
- test/controllers/FinalTaxCalculationControllerSpec.scala
Change predicate order while forming Play action; NavBar predicate requires FS data to be loaded first by FeatureSwitchPredicate;
> Hot fix nav bar bug staging

- app/controllers/predicates/NavBarPredicate.scala
> MISUV-7256: HotFix

- it/test/controllers/claimToAdjustPoa/CheckYourAnswersControllerISpec.scala
- it/test/controllers/claimToAdjustPoa/ConfirmationForAdjustingPoaControllerISpec.scala
- it/test/controllers/claimToAdjustPoa/EnterPoAAmountControllerISpec.scala
- it/test/controllers/claimToAdjustPoa/PaymentsOnAccountAdjustedControllerISpec.scala
- it/test/controllers/claimToAdjustPoa/SelectYourReasonControllerISpec.scala
- it/test/controllers/claimToAdjustPoa/WhatYouNeedToKnowControllerISpec.scala
> AwaitMongoResetsFixIts

- app/controllers/claimToAdjustPoa/CheckYourAnswersController.scala
- app/controllers/claimToAdjustPoa/ConfirmationForAdjustingPoaController.scala
- app/services/claimToAdjustPoa/ClaimToAdjustHelper.scala
- app/services/claimToAdjustPoa/ClaimToAdjustPoaCalculationService.scala
- app/services/claimToAdjustPoa/ClaimToAdjustService.scala
- app/services/claimToAdjustPoa/RecalculatePoaHelper.scala
- test/mocks/services/MockClaimToAdjustPoaCalculationService.scala
- test/services/claimToAdjust/ClaimToAdjustPoaCalculationServiceSpec.scala
Move ClaimToAdjust specific logic into designated folder/package;
> Code refactoring

- it/test/controllers/agent/optOut/ConfirmOptOutControllerISpec.scala
> MISUV-7803: enable test

- app/controllers/NextUpdatesController.scala
- app/services/optout/OptOutService.scala
- app/views/errorPages/templates/ErrorTemplatePartial.scala.html
- app/views/nextUpdates/NextUpdatesOptOut.scala.html
- it/test/controllers/NextUpdatesControllerForOptOutISpec.scala
- it/test/controllers/NextUpdatesControllerIForOptOutISpec.scala
- it/test/controllers/agent/optOut/ConfirmOptOutControllerISpec.scala
- it/test/controllers/optOut/OptOutErrorControllerISpec.scala
- it/test/helpers/agent/ComponentSpecBase.scala
- test/services/optout/OptOutServiceSpec.scala
header-html-class, reset optout intent
> MISUV-7470: header-html-class, reset optout intent

- app/views/optOut/OptOutError.scala.html
- conf/app.routes
- test/views/optOut/OptOutErrorViewSpec.scala
> MISUV-7470: fix agents path

- app/services/optout/OptOutProposition.scala
- app/services/optout/OptOutService.scala
- app/services/optout/OptOutTaxYear.scala
- test/services/optout/optoutproposition/OptOutPropositionYearsToUpdateSpec.scala
Refactors the logic for Opt Out to use the simpler TaxYear rather than the OptOutTaxYear
> MISUV-7889 opt out refactor updated years to tax year

- app/services/optout/OptOutService.scala
- test/services/optout/OptOutServiceSpec.scala
- test/services/optout/quarterlyupdates/QuarterlyUpdatesCountSpec.scala
test_code_for_quarterly_updates_counts
> MISUV-7862-test_code_for_quarterly_updates_counts

- app/services/claimToAdjustPoa/ClaimToAdjustHelper.scala
changed accepted getCalcList response from 204 -> 404 and added logging in this area
> ITSAVC E2E test hotfix 

- app/services/admin/FeatureSwitchService.scala
We need to improve monitoring around FS stage dynamic change / via FE test page:
* logging added  when we call set /setAll methods in FeatureSwitchService;
> * monitor FS state change;

- app/connectors/optout/ITSAStatusUpdateConnector.scala
- app/connectors/optout/OptOutUpdateRequestModel.scala
> MISUV-7936-reason-as-string

- app/models/nextUpdates/NextUpdatesResponseModel.scala
- it/test/controllers/TaxYearSummaryControllerISpec.scala
- it/test/controllers/agent/HomeControllerISpec.scala
- it/test/controllers/agent/NextUpdatesControllerISpec.scala
- it/test/controllers/agent/TaxYearSummaryControllerISpec.scala
- it/test/controllers/agent/manageBusinesses/add/IncomeSourceAddedControllerISpec.scala
- it/test/controllers/agent/manageBusinesses/cease/IncomeSourceCeasedObligationsControllerISpec.scala
- it/test/controllers/optOut/OptOutChooseTaxYearControllerISpec.scala
- it/test/testConstants/IncomeSourcesObligationsIntegrationTestConstants.scala
- it/test/testConstants/NextUpdatesIntegrationTestConstants.scala
- it/test/testConstants/PreviousObligationsIntegrationTestConstants.scala
- test/audit/models/TaxYearSummaryResponseAuditModelSpec.scala
- test/controllers/NextUpdatesControllerSpec.scala
- test/controllers/TaxYearSummaryControllerSpec.scala
- test/controllers/incomeSources/add/IncomeSourceAddedControllerSpec.scala
- test/controllers/incomeSources/manage/ManageObligationsControllerSpec.scala
- test/controllers/manageBusinesses/add/IncomeSourceAddedControllerSpec.scala
- test/controllers/manageBusinesses/cease/IncomeSourceCeasedObligationsControllerSpec.scala
- test/controllers/manageBusinesses/manage/ManageObligationsControllerSpec.scala
- test/models/NextUpdatesResponseModelSpec.scala
- test/services/NextUpdatesServiceSpec.scala
- test/testConstants/BusinessDetailsTestConstants.scala
- test/testConstants/NextUpdatesTestConstants.scala
- test/testConstants/PropertyDetailsTestConstants.scala
- test/testConstants/incomeSources/IncomeSourcesObligationsTestConstants.scala
> MISUV-7909-use-sealed-trait

- app/views/claimToAdjustPoa/EnterPoAAmountView.scala.html
- conf/messages
- conf/messages.cy
- it/test/controllers/claimToAdjustPoa/EnterPoAAmountControllerISpec.scala
- test/views/claimToAdjustPoa/EnterPoAAmountViewSpec.scala
updated content on enter a new amount page
> MISUV-7955-enter-poa-amount-content-changes

- conf/application.conf
Added new url string to AfterPropertySourceCreated
> MISUV-7983-fix - Choose a reporting method page and API error page

- app/audit/models/ClaimARefundAuditModel.scala
- app/connectors/FinancialDetailsConnector.scala
- app/models/creditsandrefunds/CreditAndRefundViewModel.scala
- app/models/creditsandrefunds/CreditsModel.scala
- app/models/incomeSourceDetails/TaxYear.scala
- app/services/CreditService.scala
- app/views/components/creditandrefund/creditViewRow.scala.html
- test/models/creditsandrefunds/CreditAndRefundViewModelSpec.scala
- test/models/creditsandrefunds/CreditsModelSpec.scala
- test/models/incomeSourceDetails/TaxYearSpec.scala
- test/services/CreditServiceSpec.scala
- test/testConstants/FinancialDetailsTestConstants.scala
- Use TaxYear type instead of Int / String
- Parse TaxYear directly from JSON, with validation
> MISUV-7891 | Tidying based on PR comments

- app/models/nextUpdates/NextUpdatesResponseModel.scala
- app/services/NextUpdatesService.scala
- test/services/NextUpdatesServiceSpec.scala
Remove incorrect sub-type and tidy up related code
> MISUV-8077 Correct NextUpdates/Obligations Model Hierarchy

- app/services/claimToAdjustPoa/ClaimToAdjustHelper.scala
- app/services/claimToAdjustPoa/ClaimToAdjustService.scala
* refactor getPaymentOnAccountModel method to return Either instead of raising exception on missing Poa amount(s);
* refactor getAmendablePoaViewModel method;
> MISUV-7552:  another ClaimToAdjustService refactoring

- app/services/CalculationListService.scala
- test/services/CalculationListServiceSpec.scala
> MISUV-8087-no-calculations-is-not-an-error

- app/connectors/ITSAStatusConnector.scala
- app/connectors/optout/ITSAStatusUpdateConnector.scala
- app/connectors/optout/OptOutUpdateRequestModel.scala
- app/controllers/optOut/ConfirmOptOutController.scala
- test/connectors/optout/ITSAStatusUpdateConnectorSpec.scala
- test/connectors/optout/ITSAStatusUpdateConnectorTest.scala
- test/connectors/optout/OptOutUpdateRequestModelSpec.scala
- test/controllers/optOut/ConfirmOptOutControllerSpec.scala
- test/services/optout/OptOutServiceMakeOptOutUpdateRequestSpec.scala
- test/services/optout/OptOutServiceNextUpdatesPageOptOutViewModelSpec.scala
- test/services/optout/OptOutServiceSpec.scala
- test/services/optout/optoutproposition/OptOutServiceMakeOptOutUpdateRequestSpec.scala
- test/testConstants/ITSAStatusTestConstants.scala
> Misuv 7993 log error as json

- conf/messages.cy
> MISUV-8294-fix-welsh-text

- conf/messages.cy
> MISUV-7943-add-welsh-text

- conf/messages
Changed to lowercase b instead of B
> Title of Balancing payment changed to lower case

- test/resources/OptInScenarios.tsv
- test/services/optIn/OptInPropositionExcelSpec.scala
> MISUV-8221-optin-excel-sheet-test

- conf/messages.cy
> MISUV-8358-add-welsh

- conf/messages.cy
> MISUV-8406-add-welsh

- app/services/optIn/OptInService.scala
- app/services/optIn/core/OptInProposition.scala
- test/controllers/optIn/OptInCompletedControllerSpec.scala
- test/services/optIn/OptInPropositionExcelSpec.scala
- test/services/optIn/OptInPropositionSpec.scala
Generalise the OptInProposition factory function and use it to de-duplicate construction where appropriate in the service and tests.
> Misuv 8566 streamline opt in proposition factory functions

- app/controllers/CreditAndRefundController.scala
> MISUV-8334:

- app/views/optOut/OptOutChooseTaxYear.scala.html
- conf/messages
- conf/messages.cy
- it/test/controllers/optIn/ChooseTaxYearControllerISpec.scala
- it/test/controllers/optOut/OptOutChooseTaxYearControllerISpec.scala
- test/views/optOut/OptOutChooseTaxYearViewSpec.scala
content change for the following:
https://jira.tools.tax.service.gov.uk/browse/MISUV-8500
> MISUV-8500 - opt out confirmation content change

- build.sbt
re-enable min test coverage test;
> MISUV-8753: re-eneable min test coverage in build.sbt

- app/auth/authV2/actions/AgentIsPrimaryAction.scala
- app/config/AgentItvcErrorHandler.scala
- app/controllers/agent/errors/AgentErrorController.scala
- app/views/agent/errorPages/UnauthorisedAgentView.scala.html
- conf/agent.routes
- conf/messages
- conf/messages.cy
- test/authV2/AgentIsPrimaryActionSpec.scala
- test/controllers/agent/errors/AgentErrorControllerSpec.scala
- test/mocks/MockItvcErrorHandler.scala
- test/views/agent/errorPages/UTRErrorViewSpec.scala
- test/views/agent/errorPages/UnauthorisedAgentViewSpec.scala
- added new unauthorised agent page
- updated AgentIsPrimaryActionSpec
- minor test name/folder changes
> MISUV-8696: Create the no authorisation page

- app/auth/authV2/AuthActions.scala
- app/auth/authV2/actions/AuthoriseAndRetrieve.scala
- app/config/AgentItvcErrorHandler.scala
- app/config/ItvcErrorHandler.scala
- app/config/featureswitch/FeatureSwitching.scala
- app/controllers/ReportingFrequencyPageController.scala
- app/controllers/incomeSources/add/AddIncomeSourceController.scala
- app/controllers/optIn/ChooseYearController.scala
- app/models/admin/FeatureSwitchName.scala
- app/services/optIn/OptInService.scala
- app/utils/AuthenticatorPredicate.scala
- app/views/errorPages/templates/ErrorTemplate.scala.html
- app/views/manageBusinesses/manage/ManageIncomeSourceDetails.scala.html
- conf/app.routes
- conf/application.conf
- it/test/controllers/ControllerISpecBase.scala
- it/test/controllers/InYearTaxCalculationControllerISpec.scala
- it/test/controllers/ReportingFrequencyControllerISpec.scala
- it/test/controllers/agent/ChargeSummaryControllerISpec.scala
- test/config/featureswitch/FeatureSwitchingSpec.scala
- test/controllers/RefundToTaxPayerControllerSpec.scala
- test/controllers/ReportingFrequencyPageControllerSpec.scala
- test/controllers/optIn/CheckYourAnswersControllerSpec.scala
- test/controllers/optIn/ConfirmTaxYearControllerSpec.scala
- test/mocks/controllers/predicates/MockAuthenticationPredicate.scala
- test/services/optIn/OptInServiceSpec.scala
- test/testUtils/TestSupport.scala
- test/views/manageBusinesses/manage/ManageIncomeSourceDetailsViewSpec.scala
- test/views/optIn/CheckYourAnswersViewSpec.scala
- test/views/optIn/ConfirmTaxYearViewSpec.scala
App config changes
Base -> https://github.com/hmrc/app-config-base/pull/11217/files
QA -> https://github.com/hmrc/app-config-qa/pull/23803/files
Staging -> https://github.com/hmrc/app-config-staging/pull/16230
Prod -> https://github.com/hmrc/app-config-production/pull/23762
> MISUV-8691 Add new feature switch for reporting frequency page

- conf/messages
- conf/messages.cy
- it/test/controllers/agent/optOut/SingleYearOptOutWarningControllerISpec.scala
- it/test/controllers/optOut/SingleYearOptOutWarningControllerISpec.scala
- test/views/optOut/SingleYearOptOutWarningViewSpec.scala
regarding:
'Opt out: 'opt out confirmation' page for a single year following mandated (quarterly+quarterly mandated)' (https://jira.tools.tax.service.gov.uk/browse/MISUV-8527)
content change
> MISUV-8782 - opt out confirmation content update

- app/controllers/optOut/SingleYearOptOutWarningController.scala
- it/test/controllers/NextUpdatesControllerForOptOutISpec.scala
- it/test/controllers/agent/optOut/SingleYearOptOutWarningControllerISpec.scala
- it/test/controllers/optOut/SingleYearOptOutWarningControllerISpec.scala
- test/controllers/incomeSources/add/AddBusinessAddressControllerSpec.scala
- test/controllers/incomeSources/add/AddBusinessNameControllerSpec.scala
- test/controllers/incomeSources/add/AddBusinessTradeControllerSpec.scala
- test/controllers/incomeSources/add/AddIncomeSourceControllerSpec.scala
- test/controllers/incomeSources/cease/CeaseIncomeSourceControllerSpec.scala
- test/controllers/incomeSources/cease/CheckCeaseIncomeSourceDetailsControllerSpec.scala
- test/controllers/manageBusinesses/add/AddBusinessAddressControllerSpec.scala
- test/controllers/manageBusinesses/add/AddBusinessNameControllerSpec.scala
- test/controllers/manageBusinesses/add/AddBusinessTradeControllerSpec.scala
- test/controllers/manageBusinesses/add/AddIncomeSourceControllerSpec.scala
- test/controllers/manageBusinesses/cease/CeaseIncomeSourceControllerSpec.scala
- test/controllers/manageBusinesses/cease/CheckCeaseIncomeSourceDetailsControllerSpec.scala
- test/controllers/optOut/SingleYearOptOutWarningControllerSpec.scala
- test/mocks/services/MockOptOutService.scala
- test/testUtils/TestSupport.scala
- updated SingleYearOptOutWarningController with new auth
- updated it and unit tests for primary/ supporint agent and individual users
> MISUV-8706: Update SingleYearOptOutWarningController to use new authActions

- test/views/html/helpers/injected/obligations/NextUpdatesHelperSpec.scala
* Failing tests would pass under Java11 and Java21;
> MISUV-8815: Fix failing test

- app/controllers/NextUpdatesController.scala
- app/views/nextUpdates/NextUpdates.scala.html
- app/views/nextUpdates/NextUpdatesOptOut.scala.html
- test/controllers/NextUpdatesControllerSpec.scala
- test/mocks/views/agent/MockNextUpdates.scala
- test/views/nextUpdates/NextUpdatesOptOutViewSpec.scala
- test/views/nextUpdates/NextUpdatesViewSpec.scala
- Removed tax year summary for supporting agents only
- Added view, controller and integration tests for NextUpdates
> MISUV-8859:

- app/controllers/ReportingFrequencyPageController.scala
- app/models/ReportingFrequencyViewModel.scala
- app/viewUtils/ReportingFrequencyViewUtils.scala
- app/views/ReportingFrequencyView.scala.html
- conf/messages
- conf/messages.cy
- test/controllers/ReportingFrequencyPageControllerSpec.scala
- test/viewUtils/ReportingFrequencyViewUtilsSpec.scala
- test/views/ReportingFrequencyViewSpec.scala
> MISUV-8950 Add table and content to Reporting frequency page

- app/controllers/manageBusinesses/manage/ManageIncomeSourceDetailsController.scala
- app/views/manageBusinesses/manage/ManageIncomeSourceDetails.scala.html
- it/test/controllers/manageBusinesses/manage/ManageIncomeSourceDetailsForeignPropertyControllerISpec.scala
- it/test/controllers/manageBusinesses/manage/ManageIncomeSourceDetailsSelfEmploymentControllerISpec.scala
- it/test/controllers/manageBusinesses/manage/ManageIncomeSourceDetailsUKPropertyControllerISpec.scala
- test/controllers/manageBusinesses/manage/ManageIncomeSourceDetailsForeignPropertySpec.scala
- test/controllers/manageBusinesses/manage/ManageIncomeSourceDetailsSelfEmploymentSpec.scala
- test/controllers/manageBusinesses/manage/ManageIncomeSourceDetailsUkPropertySpec.scala
- test/views/manageBusinesses/manage/ManageIncomeSourceDetailsViewSpec.scala
hiding start date inside of manage business details behind a feature switch
> MISUV-9111 Making Income Source Start Date Non-Mandatory

- app/services/WhatYouOweService.scala
- pass clientUTR to the private function;
- use named HttpStatus code instead of numerical value;
- code formatting applied across the file;
> * MISUV-9319: few more refactoring steps;

- app/testOnly/views/LoginPage.scala.html
- conf/messages
- conf/messages.cy
- it/test/connectors/AddressLookupConnectorISpec.scala
- it/test/controllers/InYearTaxCalculationControllerISpec.scala
- it/test/controllers/incomeSources/cease/IncomeSourceCeasedObligationsControllerISpec.scala
- it/test/controllers/manageBusinesses/cease/IncomeSourceCeasedObligationsControllerISpec.scala
- it/test/controllers/optIn/SingleTaxYearOptInWarningControllerISpec.scala
- run_all_tests.sh
- test/controllers/FeedbackControllerSpec.scala
- test/controllers/NotMigratedUserControllerSpec.scala
- test/controllers/PaymentHistoryControllerSpec.scala
- test/controllers/manageBusinesses/add/IncomeSourceReportingFrequencyControllerSpec.scala
- test/utils/claimToAdjust/JourneyCheckerClaimToAdjustSpec.scala
- test/utils/claimToAdjust/WithSessionAndPoaSpec.scala
- test/views/CreditAndRefundsViewSpec.scala
- test/views/HomePageViewSpec.scala
- test/views/agent/PrimaryAgentHomePageViewSpec.scala
- test/views/claimToAdjustPoa/SelectYourReasonViewSpec.scala
- test/views/manageBusinesses/ManageYourBusinessesViewSpec.scala
- test/views/manageBusinesses/add/ChooseTaxYearViewSpec.scala
- test/views/messages/ConfirmOptOutMessages.scala
- test/views/messages/ConfirmedOptOutMessages.scala
- test/views/messages/OptInCancelledViewMessages.scala
- test/views/messages/OptInCompletedViewMessages.scala
- test/views/messages/OptInSingleTaxYearWarningMessages.scala
- test/views/messages/OptOutCancelledViewMessages.scala
- test/views/messages/ReportingFrequencyViewMessages.scala
- test/views/optIn/CheckYourAnswersViewSpec.scala
- test/views/optOut/CheckOptOutAnswersViewSpec.scala
> MISUV-9571 replace 'Manage your Income Tax updates' with 'Manage your Self Assessment'

- app/views/manageBusinesses/add/AddBusinessName.scala.html
- conf/messages
- conf/messages.cy
- test/views/manageBusinesses/add/AddBusinessNameViewSpec.scala
~~Renamed related variables for clarity across codebase~~
Screenshot:
---
Ticket: [MISUV- 9599](https://jira.tools.tax.service.gov.uk/browse/MISUV-9599)
> MISUV-9599: Update AddBusinessName view and spec to reflect revised hint text

- app/controllers/incomeSources/add/AddBusinessAddressController.scala
- app/controllers/incomeSources/add/AddIncomeSourceStartDateCheckController.scala
- app/controllers/incomeSources/add/IncomeSourceCheckDetailsController.scala
- app/controllers/manageBusinesses/add/IncomeSourceCheckDetailsController.scala
- app/models/createIncomeSource/CreateIncomeSourcesRequestModel.scala
- app/models/incomeSourceDetails/viewmodels/CheckDetailsViewModel.scala
- app/services/CreateBusinessDetailsService.scala
- it/test/connectors/CreateIncomeSourceConnectorISpec.scala
- it/test/controllers/incomeSources/add/AddIncomeSourceStartDateCheckControllerISpec.scala
- it/test/helpers/IncomeSourceCheckDetailsConstants.scala
- test/audit/models/CreateIncomeSourceAuditModelSpec.scala
- test/connectors/helpers/IncomeSourcesDataHelper.scala
- test/controllers/incomeSources/add/AddBusinessAddressControllerSpec.scala
- test/controllers/incomeSources/add/AddIncomeSourceStartDateCheckControllerSpec.scala
- test/models/createIncomeSource/CreateIncomeSourcesRequestModelSpec.scala
- test/services/CreateBusinessDetailsServiceSpec.scala
- test/views/incomeSources/add/IncomeSourceCheckDetailsViewSpec.scala
- test/views/manageBusinesses/add/IncomeSourceCheckDetailsViewSpec.scala
old journey + some compilation fixes for the new journey
(this will be merged in first so that when I pull in changes from this branch onto the new journey branch there will be no conflicts)
> MISUV-9583 - moved accounting method behind the new feature switch

- app/views/manageBusinesses/add/IncomeSourceAddedObligationsView.scala.html
- conf/messages
- conf/messages.cy
in addition to the ticket [MISUV-9792](https://jira.tools.tax.service.gov.uk/browse/MISUV-9792) 
these changes include, uk/foreign property journey link fixes also, as they were part of the same issue.
> MISUV-9792

- app/config/FrontendAppConfig.scala
- app/controllers/manageBusinesses/manage/ManageIncomeSourceDetailsController.scala
- app/models/incomeSourceDetails/QuarterTypeElection.scala
- app/models/obligations/ObligationsResponseModel.scala
- app/views/incomeSources/manage/ManageIncomeSourceDetails.scala.html
- app/views/manageBusinesses/manage/ManageIncomeSourceDetailsView.scala.html
- conf/messages
- conf/messages.cy
- test/controllers/incomeSources/manage/ManageIncomeSourceDetailsForeignPropertySpec.scala
- test/controllers/incomeSources/manage/ManageIncomeSourceDetailsHelper.scala
- test/controllers/incomeSources/manage/ManageIncomeSourceDetailsSelfEmploymentSpec.scala
- test/controllers/incomeSources/manage/ManageIncomeSourceDetailsUkPropertySpec.scala
- test/controllers/manageBusinesses/manage/ManageIncomeSourceDetailsForeignPropertySpec.scala
- test/controllers/manageBusinesses/manage/ManageIncomeSourceDetailsHelper.scala
- test/controllers/manageBusinesses/manage/ManageIncomeSourceDetailsSelfEmploymentSpec.scala
- test/controllers/manageBusinesses/manage/ManageIncomeSourceDetailsUkPropertySpec.scala
- test/views/constants/ManageIncomeSourceDetailsViewConstants.scala
- test/views/incomeSources/manage/ManageIncomeSourceDetailsViewSpec.scala
- test/views/manageBusinesses/manage/ManageIncomeSourceDetailsViewSpec.scala
- test/views/messages/ManageIncomeSourceDetailsViewMessages.scala
reviewer notes:
- Tried to uncouple the keys for the old income source manage cya and the new version.
- kept most of the tests but changed some ids and such. moved messages and constants to help modularise the code to keep the view spec a little concise. 
- added the logic as boolean flags but need to test it a little to see if it matches the ask of the ticket.
> MISUV-9834 Content update to manage income sources CYA page
